package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Abrart generated by hbm2java
 */
@Entity
@Table(name="abrart"
    ,catalog="paulprod"
)
public class Abrart  implements java.io.Serializable {


     private String abrart;
     private String bezeichnung;

    public Abrart() {
    }

	
    public Abrart(String abrart) {
        this.abrart = abrart;
    }
    public Abrart(String abrart, String bezeichnung) {
       this.abrart = abrart;
       this.bezeichnung = bezeichnung;
    }
   
     @Id 
    
    @Column(name="abrart", unique=true, nullable=false, length=1)
    public String getAbrart() {
        return this.abrart;
    }
    
    public void setAbrart(String abrart) {
        this.abrart = abrart;
    }
    
    @Column(name="Bezeichnung", length=30)
    public String getBezeichnung() {
        return this.bezeichnung;
    }
    
    public void setBezeichnung(String bezeichnung) {
        this.bezeichnung = bezeichnung;
    }




}


