package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Affinisgesellschaft generated by hbm2java
 */
@Entity
@Table(name="affinisgesellschaft"
    ,catalog="paulprod"
)
public class Affinisgesellschaft  implements java.io.Serializable {


     private int hid;
     private Gp gp;
     private String gesellschaft;
     private String typ;
     private String uid;
     private String active;
     private String kuerzel;
     private byte[] logo;
     private String template;
     private Set<Mitarbeiter> mitarbeiters = new HashSet<Mitarbeiter>(0);
     private Set<HAuftrag> HAuftrags = new HashSet<HAuftrag>(0);
     private Set<Geschaeftsfeld> geschaeftsfelds = new HashSet<Geschaeftsfeld>(0);

    public Affinisgesellschaft() {
    }

	
    public Affinisgesellschaft(int hid, String gesellschaft, String active, String template) {
        this.hid = hid;
        this.gesellschaft = gesellschaft;
        this.active = active;
        this.template = template;
    }
    public Affinisgesellschaft(int hid, Gp gp, String gesellschaft, String typ, String uid, String active, String kuerzel, byte[] logo, String template, Set<Mitarbeiter> mitarbeiters, Set<HAuftrag> HAuftrags, Set<Geschaeftsfeld> geschaeftsfelds) {
       this.hid = hid;
       this.gp = gp;
       this.gesellschaft = gesellschaft;
       this.typ = typ;
       this.uid = uid;
       this.active = active;
       this.kuerzel = kuerzel;
       this.logo = logo;
       this.template = template;
       this.mitarbeiters = mitarbeiters;
       this.HAuftrags = HAuftrags;
       this.geschaeftsfelds = geschaeftsfelds;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gp")
    public Gp getGp() {
        return this.gp;
    }
    
    public void setGp(Gp gp) {
        this.gp = gp;
    }
    
    @Column(name="gesellschaft", nullable=false, length=50)
    public String getGesellschaft() {
        return this.gesellschaft;
    }
    
    public void setGesellschaft(String gesellschaft) {
        this.gesellschaft = gesellschaft;
    }
    
    @Column(name="typ", length=50)
    public String getTyp() {
        return this.typ;
    }
    
    public void setTyp(String typ) {
        this.typ = typ;
    }
    
    @Column(name="uid", length=50)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    
    @Column(name="active", nullable=false, length=1)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    
    @Column(name="kuerzel", length=10)
    public String getKuerzel() {
        return this.kuerzel;
    }
    
    public void setKuerzel(String kuerzel) {
        this.kuerzel = kuerzel;
    }
    
    @Column(name="logo")
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
    
    @Column(name="template", nullable=false, length=50)
    public String getTemplate() {
        return this.template;
    }
    
    public void setTemplate(String template) {
        this.template = template;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="affinisgesellschaft")
    public Set<Mitarbeiter> getMitarbeiters() {
        return this.mitarbeiters;
    }
    
    public void setMitarbeiters(Set<Mitarbeiter> mitarbeiters) {
        this.mitarbeiters = mitarbeiters;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="affinisgesellschaft")
    public Set<HAuftrag> getHAuftrags() {
        return this.HAuftrags;
    }
    
    public void setHAuftrags(Set<HAuftrag> HAuftrags) {
        this.HAuftrags = HAuftrags;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="affinisgesellschaft")
    public Set<Geschaeftsfeld> getGeschaeftsfelds() {
        return this.geschaeftsfelds;
    }
    
    public void setGeschaeftsfelds(Set<Geschaeftsfeld> geschaeftsfelds) {
        this.geschaeftsfelds = geschaeftsfelds;
    }




}


