package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Arbeitstage generated by hbm2java
 */
@Entity
@Table(name="arbeitstage"
    ,catalog="paulprod"
)
public class Arbeitstage  implements java.io.Serializable {


     private short jahr;
     private Short jan;
     private Short feb;
     private Short mrz;
     private Short apr;
     private Short mai;
     private Short jun;
     private Short jul;
     private Short aug;
     private Short sep;
     private Short okt;
     private Short nov;
     private Short dez;

    public Arbeitstage() {
    }

	
    public Arbeitstage(short jahr) {
        this.jahr = jahr;
    }
    public Arbeitstage(short jahr, Short jan, Short feb, Short mrz, Short apr, Short mai, Short jun, Short jul, Short aug, Short sep, Short okt, Short nov, Short dez) {
       this.jahr = jahr;
       this.jan = jan;
       this.feb = feb;
       this.mrz = mrz;
       this.apr = apr;
       this.mai = mai;
       this.jun = jun;
       this.jul = jul;
       this.aug = aug;
       this.sep = sep;
       this.okt = okt;
       this.nov = nov;
       this.dez = dez;
    }
   
     @Id 
    
    @Column(name="Jahr", unique=true, nullable=false)
    public short getJahr() {
        return this.jahr;
    }
    
    public void setJahr(short jahr) {
        this.jahr = jahr;
    }
    
    @Column(name="Jan")
    public Short getJan() {
        return this.jan;
    }
    
    public void setJan(Short jan) {
        this.jan = jan;
    }
    
    @Column(name="Feb")
    public Short getFeb() {
        return this.feb;
    }
    
    public void setFeb(Short feb) {
        this.feb = feb;
    }
    
    @Column(name="Mrz")
    public Short getMrz() {
        return this.mrz;
    }
    
    public void setMrz(Short mrz) {
        this.mrz = mrz;
    }
    
    @Column(name="Apr")
    public Short getApr() {
        return this.apr;
    }
    
    public void setApr(Short apr) {
        this.apr = apr;
    }
    
    @Column(name="Mai")
    public Short getMai() {
        return this.mai;
    }
    
    public void setMai(Short mai) {
        this.mai = mai;
    }
    
    @Column(name="Jun")
    public Short getJun() {
        return this.jun;
    }
    
    public void setJun(Short jun) {
        this.jun = jun;
    }
    
    @Column(name="Jul")
    public Short getJul() {
        return this.jul;
    }
    
    public void setJul(Short jul) {
        this.jul = jul;
    }
    
    @Column(name="Aug")
    public Short getAug() {
        return this.aug;
    }
    
    public void setAug(Short aug) {
        this.aug = aug;
    }
    
    @Column(name="Sep")
    public Short getSep() {
        return this.sep;
    }
    
    public void setSep(Short sep) {
        this.sep = sep;
    }
    
    @Column(name="Okt")
    public Short getOkt() {
        return this.okt;
    }
    
    public void setOkt(Short okt) {
        this.okt = okt;
    }
    
    @Column(name="Nov")
    public Short getNov() {
        return this.nov;
    }
    
    public void setNov(Short nov) {
        this.nov = nov;
    }
    
    @Column(name="Dez")
    public Short getDez() {
        return this.dez;
    }
    
    public void setDez(Short dez) {
        this.dez = dez;
    }




}


