package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AufgabeMaAssocId generated by hbm2java
 */
@Embeddable
public class AufgabeMaAssocId  implements java.io.Serializable {


     private int mitarbeiterid;
     private int aufgabeid;

    public AufgabeMaAssocId() {
    }

    public AufgabeMaAssocId(int mitarbeiterid, int aufgabeid) {
       this.mitarbeiterid = mitarbeiterid;
       this.aufgabeid = aufgabeid;
    }
   

    @Column(name="mitarbeiterid", nullable=false)
    public int getMitarbeiterid() {
        return this.mitarbeiterid;
    }
    
    public void setMitarbeiterid(int mitarbeiterid) {
        this.mitarbeiterid = mitarbeiterid;
    }

    @Column(name="aufgabeid", nullable=false)
    public int getAufgabeid() {
        return this.aufgabeid;
    }
    
    public void setAufgabeid(int aufgabeid) {
        this.aufgabeid = aufgabeid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AufgabeMaAssocId) ) return false;
		 AufgabeMaAssocId castOther = ( AufgabeMaAssocId ) other; 
         
		 return (this.getMitarbeiterid()==castOther.getMitarbeiterid())
 && (this.getAufgabeid()==castOther.getAufgabeid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMitarbeiterid();
         result = 37 * result + this.getAufgabeid();
         return result;
   }   


}


