package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Geschaeftsfeld generated by hbm2java
 */
@Entity
@Table(name="geschaeftsfeld"
    ,catalog="paulprod"
)
public class Geschaeftsfeld  implements java.io.Serializable {


     private int hid;
     private Affinisgesellschaft affinisgesellschaft;
     private Mitarbeiter mitarbeiter;
     private String gfname;
     private Double tantiemesatz;
     private String active;
     private Set<HAuftrag> HAuftrags = new HashSet<HAuftrag>(0);

    public Geschaeftsfeld() {
    }

	
    public Geschaeftsfeld(int hid, String gfname, String active) {
        this.hid = hid;
        this.gfname = gfname;
        this.active = active;
    }
    public Geschaeftsfeld(int hid, Affinisgesellschaft affinisgesellschaft, Mitarbeiter mitarbeiter, String gfname, Double tantiemesatz, String active, Set<HAuftrag> HAuftrags) {
       this.hid = hid;
       this.affinisgesellschaft = affinisgesellschaft;
       this.mitarbeiter = mitarbeiter;
       this.gfname = gfname;
       this.tantiemesatz = tantiemesatz;
       this.active = active;
       this.HAuftrags = HAuftrags;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="affinisgesellschaft")
    public Affinisgesellschaft getAffinisgesellschaft() {
        return this.affinisgesellschaft;
    }
    
    public void setAffinisgesellschaft(Affinisgesellschaft affinisgesellschaft) {
        this.affinisgesellschaft = affinisgesellschaft;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mitarbeiter")
    public Mitarbeiter getMitarbeiter() {
        return this.mitarbeiter;
    }
    
    public void setMitarbeiter(Mitarbeiter mitarbeiter) {
        this.mitarbeiter = mitarbeiter;
    }
    
    @Column(name="gfname", nullable=false)
    public String getGfname() {
        return this.gfname;
    }
    
    public void setGfname(String gfname) {
        this.gfname = gfname;
    }
    
    @Column(name="tantiemesatz", precision=22, scale=0)
    public Double getTantiemesatz() {
        return this.tantiemesatz;
    }
    
    public void setTantiemesatz(Double tantiemesatz) {
        this.tantiemesatz = tantiemesatz;
    }
    
    @Column(name="active", nullable=false, length=1)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="geschaeftsfeld")
    public Set<HAuftrag> getHAuftrags() {
        return this.HAuftrags;
    }
    
    public void setHAuftrags(Set<HAuftrag> HAuftrags) {
        this.HAuftrags = HAuftrags;
    }




}


