package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HAuftragMitarbeiterAssignmentAuditTrail generated by hbm2java
 */
@Entity
@Table(name="h_auftrag_mitarbeiter_assignment_audit_trail"
    ,catalog="paulprod"
)
public class HAuftragMitarbeiterAssignmentAuditTrail  implements java.io.Serializable {


     private Integer id;
     private Date auditTrailDatum;
     private Integer hid;
     private int auftrag;
     private int role;
     private int mitarbeiterid;
     private Date HCreatedat;
     private Integer HCreatedby;
     private Date HModifiedat;
     private Integer HModifiedby;

    public HAuftragMitarbeiterAssignmentAuditTrail() {
    }

	
    public HAuftragMitarbeiterAssignmentAuditTrail(int auftrag, int role, int mitarbeiterid) {
        this.auftrag = auftrag;
        this.role = role;
        this.mitarbeiterid = mitarbeiterid;
    }
    public HAuftragMitarbeiterAssignmentAuditTrail(Date auditTrailDatum, Integer hid, int auftrag, int role, int mitarbeiterid, Date HCreatedat, Integer HCreatedby, Date HModifiedat, Integer HModifiedby) {
       this.auditTrailDatum = auditTrailDatum;
       this.hid = hid;
       this.auftrag = auftrag;
       this.role = role;
       this.mitarbeiterid = mitarbeiterid;
       this.HCreatedat = HCreatedat;
       this.HCreatedby = HCreatedby;
       this.HModifiedat = HModifiedat;
       this.HModifiedby = HModifiedby;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="audit_trail_datum", length=19)
    public Date getAuditTrailDatum() {
        return this.auditTrailDatum;
    }
    
    public void setAuditTrailDatum(Date auditTrailDatum) {
        this.auditTrailDatum = auditTrailDatum;
    }
    
    @Column(name="hid")
    public Integer getHid() {
        return this.hid;
    }
    
    public void setHid(Integer hid) {
        this.hid = hid;
    }
    
    @Column(name="auftrag", nullable=false)
    public int getAuftrag() {
        return this.auftrag;
    }
    
    public void setAuftrag(int auftrag) {
        this.auftrag = auftrag;
    }
    
    @Column(name="role", nullable=false)
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }
    
    @Column(name="mitarbeiterid", nullable=false)
    public int getMitarbeiterid() {
        return this.mitarbeiterid;
    }
    
    public void setMitarbeiterid(int mitarbeiterid) {
        this.mitarbeiterid = mitarbeiterid;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="h_createdat", length=10)
    public Date getHCreatedat() {
        return this.HCreatedat;
    }
    
    public void setHCreatedat(Date HCreatedat) {
        this.HCreatedat = HCreatedat;
    }
    
    @Column(name="h_createdby")
    public Integer getHCreatedby() {
        return this.HCreatedby;
    }
    
    public void setHCreatedby(Integer HCreatedby) {
        this.HCreatedby = HCreatedby;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="h_modifiedat", length=10)
    public Date getHModifiedat() {
        return this.HModifiedat;
    }
    
    public void setHModifiedat(Date HModifiedat) {
        this.HModifiedat = HModifiedat;
    }
    
    @Column(name="h_modifiedby")
    public Integer getHModifiedby() {
        return this.HModifiedby;
    }
    
    public void setHModifiedby(Integer HModifiedby) {
        this.HModifiedby = HModifiedby;
    }




}


