package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HAufgabe generated by hbm2java
 */
@Entity
@Table(name = "h_aufgabe", catalog = "paulprod")
public class HAufgabe implements java.io.Serializable {

    private int hid;
    private HAuftrag HAuftrag;
    private int aufgabennummer;
    private Integer parentaufgabe;
    private String cr;
    private String aufgabe;
    private Date beginn;
    private Date ende;
    private String aufgabenstatus;
    private Double budgetgrenze;
    private Double leistungsgrenze;
    private String leistungsort;
    private String freigabebuchung;
    private String active;
    private String kostenstellennummer;
    private Date HCreatedat;
    private Integer HCreatedby;
    private Date HModifiedat;
    private Integer HModifiedby;
    private String hinweis;
    private Set<AufgabeMaAssoc> aufgabeMaAssocs = new HashSet<AufgabeMaAssoc>(0);
    private Set<HEinsatzplan> HEinsatzplans = new HashSet<HEinsatzplan>(0);
    private Set<PQObjekt> PQObjekts = new HashSet<PQObjekt>(0);

    public HAufgabe() {
    }

    public HAufgabe(int hid, HAuftrag HAuftrag, int aufgabennummer, String freigabebuchung, String active, String kostenstellennummer) {
        this.hid = hid;
        this.HAuftrag = HAuftrag;
        this.aufgabennummer = aufgabennummer;
        this.freigabebuchung = freigabebuchung;
        this.active = active;
        this.kostenstellennummer = kostenstellennummer;
    }

    public HAufgabe(int hid, HAuftrag HAuftrag, int aufgabennummer, Integer parentaufgabe, String cr, String aufgabe, Date beginn, Date ende, String aufgabenstatus, Double budgetgrenze, Double leistungsgrenze, String leistungsort, String freigabebuchung, String active, String kostenstellennummer, Date HCreatedat, Integer HCreatedby, Date HModifiedat, Integer HModifiedby, String hinweis, Set<AufgabeMaAssoc> aufgabeMaAssocs, Set<HEinsatzplan> HEinsatzplans, Set<PQObjekt> PQObjekts) {
        this.hid = hid;
        this.HAuftrag = HAuftrag;
        this.aufgabennummer = aufgabennummer;
        this.parentaufgabe = parentaufgabe;
        this.cr = cr;
        this.aufgabe = aufgabe;
        this.beginn = beginn;
        this.ende = ende;
        this.aufgabenstatus = aufgabenstatus;
        this.budgetgrenze = budgetgrenze;
        this.leistungsgrenze = leistungsgrenze;
        this.leistungsort = leistungsort;
        this.freigabebuchung = freigabebuchung;
        this.active = active;
        this.kostenstellennummer = kostenstellennummer;
        this.HCreatedat = HCreatedat;
        this.HCreatedby = HCreatedby;
        this.HModifiedat = HModifiedat;
        this.HModifiedby = HModifiedby;
        this.hinweis = hinweis;
        this.aufgabeMaAssocs = aufgabeMaAssocs;
        this.HEinsatzplans = HEinsatzplans;
        this.PQObjekts = PQObjekts;
    }

    @Id
    @Column(name = "hid", unique = true, nullable = false)
    public int getHid() {
        return this.hid;
    }

    public void setHid(int hid) {
        this.hid = hid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "auftrag", nullable = false)
    public HAuftrag getHAuftrag() {
        return this.HAuftrag;
    }

    public void setHAuftrag(HAuftrag HAuftrag) {
        this.HAuftrag = HAuftrag;
    }

    @Column(name = "aufgabennummer", nullable = false)
    public int getAufgabennummer() {
        return this.aufgabennummer;
    }

    public void setAufgabennummer(int aufgabennummer) {
        this.aufgabennummer = aufgabennummer;
    }

    @Column(name = "parentaufgabe")
    public Integer getParentaufgabe() {
        return this.parentaufgabe;
    }

    public void setParentaufgabe(Integer parentaufgabe) {
        this.parentaufgabe = parentaufgabe;
    }

    @Column(name = "cr")
    public String getCr() {
        return this.cr;
    }

    public void setCr(String cr) {
        this.cr = cr;
    }

    @Column(name = "aufgabe")
    public String getAufgabe() {
        return this.aufgabe;
    }

    public void setAufgabe(String aufgabe) {
        this.aufgabe = aufgabe;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "beginn", length = 10)
    public Date getBeginn() {
        return this.beginn;
    }

    public void setBeginn(Date beginn) {
        this.beginn = beginn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ende", length = 10)
    public Date getEnde() {
        return this.ende;
    }

    public void setEnde(Date ende) {
        this.ende = ende;
    }

    @Column(name = "aufgabenstatus")
    public String getAufgabenstatus() {
        return this.aufgabenstatus;
    }

    public void setAufgabenstatus(String aufgabenstatus) {
        this.aufgabenstatus = aufgabenstatus;
    }

    @Column(name = "budgetgrenze", precision = 22, scale = 0)
    public Double getBudgetgrenze() {
        return this.budgetgrenze;
    }

    public void setBudgetgrenze(Double budgetgrenze) {
        this.budgetgrenze = budgetgrenze;
    }

    @Column(name = "leistungsgrenze", precision = 22, scale = 0)
    public Double getLeistungsgrenze() {
        return this.leistungsgrenze;
    }

    public void setLeistungsgrenze(Double leistungsgrenze) {
        this.leistungsgrenze = leistungsgrenze;
    }

    @Column(name = "leistungsort")
    public String getLeistungsort() {
        return this.leistungsort;
    }

    public void setLeistungsort(String leistungsort) {
        this.leistungsort = leistungsort;
    }

    @Column(name = "freigabebuchung", nullable = false, length = 1)
    public String getFreigabebuchung() {
        return this.freigabebuchung;
    }

    public void setFreigabebuchung(String freigabebuchung) {
        this.freigabebuchung = freigabebuchung;
    }

    @Column(name = "active", nullable = false, length = 1)
    public String getActive() {
        return this.active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    @Column(name = "kostenstellennummer", nullable = false)
    public String getKostenstellennummer() {
        return this.kostenstellennummer;
    }

    public void setKostenstellennummer(String kostenstellennummer) {
        this.kostenstellennummer = kostenstellennummer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "h_createdat", length = 10)
    public Date getHCreatedat() {
        return this.HCreatedat;
    }

    public void setHCreatedat(Date HCreatedat) {
        this.HCreatedat = HCreatedat;
    }

    @Column(name = "h_createdby")
    public Integer getHCreatedby() {
        return this.HCreatedby;
    }

    public void setHCreatedby(Integer HCreatedby) {
        this.HCreatedby = HCreatedby;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "h_modifiedat", length = 10)
    public Date getHModifiedat() {
        return this.HModifiedat;
    }

    public void setHModifiedat(Date HModifiedat) {
        this.HModifiedat = HModifiedat;
    }

    @Column(name = "h_modifiedby")
    public Integer getHModifiedby() {
        return this.HModifiedby;
    }

    public void setHModifiedby(Integer HModifiedby) {
        this.HModifiedby = HModifiedby;
    }

    @Column(name = "hinweis")
    public String getHinweis() {
        return this.hinweis;
    }

    public void setHinweis(String hinweis) {
        this.hinweis = hinweis;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "HAufgabe")
    public Set<AufgabeMaAssoc> getAufgabeMaAssocs() {
        return this.aufgabeMaAssocs;
    }

    public void setAufgabeMaAssocs(Set<AufgabeMaAssoc> aufgabeMaAssocs) {
        this.aufgabeMaAssocs = aufgabeMaAssocs;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "HAufgabe")
    public Set<HEinsatzplan> getHEinsatzplans() {
        return this.HEinsatzplans;
    }

    public void setHEinsatzplans(Set<HEinsatzplan> HEinsatzplans) {
        this.HEinsatzplans = HEinsatzplans;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "HAufgabe")
    public Set<PQObjekt> getPQObjekts() {
        return this.PQObjekts;
    }

    public void setPQObjekts(Set<PQObjekt> PQObjekts) {
        this.PQObjekts = PQObjekts;
    }

    @Override
    public boolean equals(Object object) {
        // Basic checks.
        if (object == this) {
            return true;
        }
        if (object == null || getClass() != object.getClass()) {
            return false;
        }

        // Property checks.
        HAufgabe other = (HAufgabe) object;
        if (aufgabe == null ? other.aufgabe != null : !aufgabe.equals(other.aufgabe)) {
            return false;
        }


        // All passed.
        return true;
    }
}
