package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HAuftragUserAssignmentId generated by hbm2java
 */
@Embeddable
public class HAuftragUserAssignmentId  implements java.io.Serializable {


     private int auftrag;
     private int role;
     private int useraccount;

    public HAuftragUserAssignmentId() {
    }

    public HAuftragUserAssignmentId(int auftrag, int role, int useraccount) {
       this.auftrag = auftrag;
       this.role = role;
       this.useraccount = useraccount;
    }
   

    @Column(name="auftrag", nullable=false)
    public int getAuftrag() {
        return this.auftrag;
    }
    
    public void setAuftrag(int auftrag) {
        this.auftrag = auftrag;
    }

    @Column(name="role", nullable=false)
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }

    @Column(name="useraccount", nullable=false)
    public int getUseraccount() {
        return this.useraccount;
    }
    
    public void setUseraccount(int useraccount) {
        this.useraccount = useraccount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HAuftragUserAssignmentId) ) return false;
		 HAuftragUserAssignmentId castOther = ( HAuftragUserAssignmentId ) other; 
         
		 return (this.getAuftrag()==castOther.getAuftrag())
 && (this.getRole()==castOther.getRole())
 && (this.getUseraccount()==castOther.getUseraccount());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAuftrag();
         result = 37 * result + this.getRole();
         result = 37 * result + this.getUseraccount();
         return result;
   }   


}


