package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HAuftrag generated by hbm2java
 */
@Entity
@Table(name = "h_auftrag", catalog = "paulprod")
public class HAuftrag implements java.io.Serializable {

    private int hid;
    private Geschaeftsfeld geschaeftsfeld;
    private LeistungseinheitMinmaxAssoc leistungseinheitMinmaxAssoc;
    private Gp gp;
    private Branche branche;
    private Kostenstelle kostenstelle;
    private Affinisgesellschaft affinisgesellschaft;
    private String auftragsnummer;
    private String name;
    private String bezeichnung;
    private String auftragsart;
    private String beschreibung;
    private Date beginn;
    private Date ende;
    private String auftragstatus;
    private String abrechnungsart;
    private Double budgetgrenze;
    private Double leistungsgrenze;
    private Double vertriebstantiemesatz;
    private String ansprechpartner;
    private String referenznummerkunde;
    private String rechnungsanschrift;
    private String rechnungssprache;
    private Integer abrechnungstag;
    private String rechnungsanlagen;
    private String waehrung;
    private String rkverrechnung;
    private Double rksatz;
    private Double mwst;
    private Integer zahlfrist;
    private String freigabebuchung;
    private String bemerkungen;
    private String active;
    private Double fakturierungssatz;
    private String zeitennachweis;
    private String zahlungsart;
    private Date HCreatedat;
    private Integer HCreatedby;
    private Date HModifiedat;
    private Integer HModifiedby;
    private String hinweis;
    private String plTantieme;
    private String leistungsinfo;
    private String projektakte;
    private String projektlink;
    private String projektlinkBeschreibung;
    private Set<HAuftragUserAssignment> HAuftragUserAssignments = new HashSet<HAuftragUserAssignment>(0);
    private Set<PQProjekt> PQProjekts = new HashSet<PQProjekt>(0);
    private Set<HAuftragMitarbeiterAssignment> HAuftragMitarbeiterAssignments = new HashSet<HAuftragMitarbeiterAssignment>(0);
    private Set<HAufgabe> HAufgabes = new HashSet<HAufgabe>(0);

    public HAuftrag() {
    }

    public HAuftrag(int hid, LeistungseinheitMinmaxAssoc leistungseinheitMinmaxAssoc, Branche branche, Affinisgesellschaft affinisgesellschaft, String freigabebuchung, String active, String zeitennachweis) {
        this.hid = hid;
        this.leistungseinheitMinmaxAssoc = leistungseinheitMinmaxAssoc;
        this.branche = branche;
        this.affinisgesellschaft = affinisgesellschaft;
        this.freigabebuchung = freigabebuchung;
        this.active = active;
        this.zeitennachweis = zeitennachweis;
    }

    public HAuftrag(int hid, Geschaeftsfeld geschaeftsfeld, LeistungseinheitMinmaxAssoc leistungseinheitMinmaxAssoc, Gp gp, Branche branche, Kostenstelle kostenstelle, Affinisgesellschaft affinisgesellschaft, String auftragsnummer, String name, String bezeichnung, String auftragsart, String beschreibung, Date beginn, Date ende, String auftragstatus, String abrechnungsart, Double budgetgrenze, Double leistungsgrenze, Double vertriebstantiemesatz, String ansprechpartner, String referenznummerkunde, String rechnungsanschrift, String rechnungssprache, Integer abrechnungstag, String rechnungsanlagen, String waehrung, String rkverrechnung, Double rksatz, Double mwst, Integer zahlfrist, String freigabebuchung, String bemerkungen, String active, Double fakturierungssatz, String zeitennachweis, String zahlungsart, Date HCreatedat, Integer HCreatedby, Date HModifiedat, Integer HModifiedby, String hinweis, String plTantieme, String leistungsinfo, String projektakte, String projektlink, String projektlinkBeschreibung, Set<HAuftragUserAssignment> HAuftragUserAssignments, Set<PQProjekt> PQProjekts, Set<HAuftragMitarbeiterAssignment> HAuftragMitarbeiterAssignments, Set<HAufgabe> HAufgabes) {
        this.hid = hid;
        this.geschaeftsfeld = geschaeftsfeld;
        this.leistungseinheitMinmaxAssoc = leistungseinheitMinmaxAssoc;
        this.gp = gp;
        this.branche = branche;
        this.kostenstelle = kostenstelle;
        this.affinisgesellschaft = affinisgesellschaft;
        this.auftragsnummer = auftragsnummer;
        this.name = name;
        this.bezeichnung = bezeichnung;
        this.auftragsart = auftragsart;
        this.beschreibung = beschreibung;
        this.beginn = beginn;
        this.ende = ende;
        this.auftragstatus = auftragstatus;
        this.abrechnungsart = abrechnungsart;
        this.budgetgrenze = budgetgrenze;
        this.leistungsgrenze = leistungsgrenze;
        this.vertriebstantiemesatz = vertriebstantiemesatz;
        this.ansprechpartner = ansprechpartner;
        this.referenznummerkunde = referenznummerkunde;
        this.rechnungsanschrift = rechnungsanschrift;
        this.rechnungssprache = rechnungssprache;
        this.abrechnungstag = abrechnungstag;
        this.rechnungsanlagen = rechnungsanlagen;
        this.waehrung = waehrung;
        this.rkverrechnung = rkverrechnung;
        this.rksatz = rksatz;
        this.mwst = mwst;
        this.zahlfrist = zahlfrist;
        this.freigabebuchung = freigabebuchung;
        this.bemerkungen = bemerkungen;
        this.active = active;
        this.fakturierungssatz = fakturierungssatz;
        this.zeitennachweis = zeitennachweis;
        this.zahlungsart = zahlungsart;
        this.HCreatedat = HCreatedat;
        this.HCreatedby = HCreatedby;
        this.HModifiedat = HModifiedat;
        this.HModifiedby = HModifiedby;
        this.hinweis = hinweis;
        this.plTantieme = plTantieme;
        this.leistungsinfo = leistungsinfo;
        this.projektakte = projektakte;
        this.projektlink = projektlink;
        this.projektlinkBeschreibung = projektlinkBeschreibung;
        this.HAuftragUserAssignments = HAuftragUserAssignments;
        this.PQProjekts = PQProjekts;
        this.HAuftragMitarbeiterAssignments = HAuftragMitarbeiterAssignments;
        this.HAufgabes = HAufgabes;
    }

    @Id
    @Column(name = "hid", unique = true, nullable = false)
    public int getHid() {
        return this.hid;
    }

    public void setHid(int hid) {
        this.hid = hid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "geschaeftsfeld")
    public Geschaeftsfeld getGeschaeftsfeld() {
        return this.geschaeftsfeld;
    }

    public void setGeschaeftsfeld(Geschaeftsfeld geschaeftsfeld) {
        this.geschaeftsfeld = geschaeftsfeld;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "einheitminmax", nullable = false)
    public LeistungseinheitMinmaxAssoc getLeistungseinheitMinmaxAssoc() {
        return this.leistungseinheitMinmaxAssoc;
    }

    public void setLeistungseinheitMinmaxAssoc(LeistungseinheitMinmaxAssoc leistungseinheitMinmaxAssoc) {
        this.leistungseinheitMinmaxAssoc = leistungseinheitMinmaxAssoc;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gp")
    public Gp getGp() {
        return this.gp;
    }

    public void setGp(Gp gp) {
        this.gp = gp;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brancheid", nullable = false)
    public Branche getBranche() {
        return this.branche;
    }

    public void setBranche(Branche branche) {
        this.branche = branche;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "kostenstelle_hid")
    public Kostenstelle getKostenstelle() {
        return this.kostenstelle;
    }

    public void setKostenstelle(Kostenstelle kostenstelle) {
        this.kostenstelle = kostenstelle;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gesellschaft", nullable = false)
    public Affinisgesellschaft getAffinisgesellschaft() {
        return this.affinisgesellschaft;
    }

    public void setAffinisgesellschaft(Affinisgesellschaft affinisgesellschaft) {
        this.affinisgesellschaft = affinisgesellschaft;
    }

    @Column(name = "auftragsnummer", length = 50)
    public String getAuftragsnummer() {
        return this.auftragsnummer;
    }

    public void setAuftragsnummer(String auftragsnummer) {
        this.auftragsnummer = auftragsnummer;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "bezeichnung")
    public String getBezeichnung() {
        return this.bezeichnung;
    }

    public void setBezeichnung(String bezeichnung) {
        this.bezeichnung = bezeichnung;
    }

    @Column(name = "auftragsart", length = 50)
    public String getAuftragsart() {
        return this.auftragsart;
    }

    public void setAuftragsart(String auftragsart) {
        this.auftragsart = auftragsart;
    }

    @Column(name = "beschreibung")
    public String getBeschreibung() {
        return this.beschreibung;
    }

    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "beginn", length = 10)
    public Date getBeginn() {
        return this.beginn;
    }

    public void setBeginn(Date beginn) {
        this.beginn = beginn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ende", length = 10)
    public Date getEnde() {
        return this.ende;
    }

    public void setEnde(Date ende) {
        this.ende = ende;
    }

    @Column(name = "auftragstatus", length = 50)
    public String getAuftragstatus() {
        return this.auftragstatus;
    }

    public void setAuftragstatus(String auftragstatus) {
        this.auftragstatus = auftragstatus;
    }

    @Column(name = "abrechnungsart", length = 1)
    public String getAbrechnungsart() {
        return this.abrechnungsart;
    }

    public void setAbrechnungsart(String abrechnungsart) {
        this.abrechnungsart = abrechnungsart;
    }

    @Column(name = "budgetgrenze", precision = 22, scale = 0)
    public Double getBudgetgrenze() {
        return this.budgetgrenze;
    }

    public void setBudgetgrenze(Double budgetgrenze) {
        this.budgetgrenze = budgetgrenze;
    }

    @Column(name = "leistungsgrenze", precision = 22, scale = 0)
    public Double getLeistungsgrenze() {
        return this.leistungsgrenze;
    }

    public void setLeistungsgrenze(Double leistungsgrenze) {
        this.leistungsgrenze = leistungsgrenze;
    }

    @Column(name = "vertriebstantiemesatz", precision = 22, scale = 0)
    public Double getVertriebstantiemesatz() {
        return this.vertriebstantiemesatz;
    }

    public void setVertriebstantiemesatz(Double vertriebstantiemesatz) {
        this.vertriebstantiemesatz = vertriebstantiemesatz;
    }

    @Column(name = "ansprechpartner")
    public String getAnsprechpartner() {
        return this.ansprechpartner;
    }

    public void setAnsprechpartner(String ansprechpartner) {
        this.ansprechpartner = ansprechpartner;
    }

    @Column(name = "referenznummerkunde")
    public String getReferenznummerkunde() {
        return this.referenznummerkunde;
    }

    public void setReferenznummerkunde(String referenznummerkunde) {
        this.referenznummerkunde = referenznummerkunde;
    }

    @Column(name = "rechnungsanschrift")
    public String getRechnungsanschrift() {
        return this.rechnungsanschrift;
    }

    public void setRechnungsanschrift(String rechnungsanschrift) {
        this.rechnungsanschrift = rechnungsanschrift;
    }

    @Column(name = "rechnungssprache", length = 5)
    public String getRechnungssprache() {
        return this.rechnungssprache;
    }

    public void setRechnungssprache(String rechnungssprache) {
        this.rechnungssprache = rechnungssprache;
    }

    @Column(name = "abrechnungstag")
    public Integer getAbrechnungstag() {
        return this.abrechnungstag;
    }

    public void setAbrechnungstag(Integer abrechnungstag) {
        this.abrechnungstag = abrechnungstag;
    }

    @Column(name = "rechnungsanlagen")
    public String getRechnungsanlagen() {
        return this.rechnungsanlagen;
    }

    public void setRechnungsanlagen(String rechnungsanlagen) {
        this.rechnungsanlagen = rechnungsanlagen;
    }

    @Column(name = "waehrung", length = 5)
    public String getWaehrung() {
        return this.waehrung;
    }

    public void setWaehrung(String waehrung) {
        this.waehrung = waehrung;
    }

    @Column(name = "rkverrechnung", length = 1)
    public String getRkverrechnung() {
        return this.rkverrechnung;
    }

    public void setRkverrechnung(String rkverrechnung) {
        this.rkverrechnung = rkverrechnung;
    }

    @Column(name = "rksatz", precision = 22, scale = 0)
    public Double getRksatz() {
        return this.rksatz;
    }

    public void setRksatz(Double rksatz) {
        this.rksatz = rksatz;
    }

    @Column(name = "mwst", precision = 22, scale = 0)
    public Double getMwst() {
        return this.mwst;
    }

    public void setMwst(Double mwst) {
        this.mwst = mwst;
    }

    @Column(name = "zahlfrist")
    public Integer getZahlfrist() {
        return this.zahlfrist;
    }

    public void setZahlfrist(Integer zahlfrist) {
        this.zahlfrist = zahlfrist;
    }

    @Column(name = "freigabebuchung", nullable = false, length = 1)
    public String getFreigabebuchung() {
        return this.freigabebuchung;
    }

    public void setFreigabebuchung(String freigabebuchung) {
        this.freigabebuchung = freigabebuchung;
    }

    @Column(name = "bemerkungen", length = 65535)
    public String getBemerkungen() {
        return this.bemerkungen;
    }

    public void setBemerkungen(String bemerkungen) {
        this.bemerkungen = bemerkungen;
    }

    @Column(name = "active", nullable = false, length = 1)
    public String getActive() {
        return this.active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    @Column(name = "fakturierungssatz", precision = 22, scale = 0)
    public Double getFakturierungssatz() {
        return this.fakturierungssatz;
    }

    public void setFakturierungssatz(Double fakturierungssatz) {
        this.fakturierungssatz = fakturierungssatz;
    }

    @Column(name = "zeitennachweis", nullable = false, length = 1)
    public String getZeitennachweis() {
        return this.zeitennachweis;
    }

    public void setZeitennachweis(String zeitennachweis) {
        this.zeitennachweis = zeitennachweis;
    }

    @Column(name = "zahlungsart", length = 1)
    public String getZahlungsart() {
        return this.zahlungsart;
    }

    public void setZahlungsart(String zahlungsart) {
        this.zahlungsart = zahlungsart;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "h_createdat", length = 10)
    public Date getHCreatedat() {
        return this.HCreatedat;
    }

    public void setHCreatedat(Date HCreatedat) {
        this.HCreatedat = HCreatedat;
    }

    @Column(name = "h_createdby")
    public Integer getHCreatedby() {
        return this.HCreatedby;
    }

    public void setHCreatedby(Integer HCreatedby) {
        this.HCreatedby = HCreatedby;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "h_modifiedat", length = 10)
    public Date getHModifiedat() {
        return this.HModifiedat;
    }

    public void setHModifiedat(Date HModifiedat) {
        this.HModifiedat = HModifiedat;
    }

    @Column(name = "h_modifiedby")
    public Integer getHModifiedby() {
        return this.HModifiedby;
    }

    public void setHModifiedby(Integer HModifiedby) {
        this.HModifiedby = HModifiedby;
    }

    @Column(name = "hinweis", length = 65535)
    public String getHinweis() {
        return this.hinweis;
    }

    public void setHinweis(String hinweis) {
        this.hinweis = hinweis;
    }

    @Column(name = "pl_tantieme", length = 3)
    public String getPlTantieme() {
        return this.plTantieme;
    }

    public void setPlTantieme(String plTantieme) {
        this.plTantieme = plTantieme;
    }

    @Column(name = "leistungsinfo")
    public String getLeistungsinfo() {
        return this.leistungsinfo;
    }

    public void setLeistungsinfo(String leistungsinfo) {
        this.leistungsinfo = leistungsinfo;
    }

    @Column(name = "projektakte")
    public String getProjektakte() {
        return this.projektakte;
    }

    public void setProjektakte(String projektakte) {
        this.projektakte = projektakte;
    }

    @Column(name = "projektlink")
    public String getProjektlink() {
        return this.projektlink;
    }

    public void setProjektlink(String projektlink) {
        this.projektlink = projektlink;
    }

    @Column(name = "projektlink_beschreibung")
    public String getProjektlinkBeschreibung() {
        return this.projektlinkBeschreibung;
    }

    public void setProjektlinkBeschreibung(String projektlinkBeschreibung) {
        this.projektlinkBeschreibung = projektlinkBeschreibung;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "HAuftrag")
    public Set<HAuftragUserAssignment> getHAuftragUserAssignments() {
        return this.HAuftragUserAssignments;
    }

    public void setHAuftragUserAssignments(Set<HAuftragUserAssignment> HAuftragUserAssignments) {
        this.HAuftragUserAssignments = HAuftragUserAssignments;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "HAuftrag")
    public Set<PQProjekt> getPQProjekts() {
        return this.PQProjekts;
    }

    public void setPQProjekts(Set<PQProjekt> PQProjekts) {
        this.PQProjekts = PQProjekts;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "HAuftrag")
    public Set<HAuftragMitarbeiterAssignment> getHAuftragMitarbeiterAssignments() {
        return this.HAuftragMitarbeiterAssignments;
    }

    public void setHAuftragMitarbeiterAssignments(Set<HAuftragMitarbeiterAssignment> HAuftragMitarbeiterAssignments) {
        this.HAuftragMitarbeiterAssignments = HAuftragMitarbeiterAssignments;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "HAuftrag")
    public Set<HAufgabe> getHAufgabes() {
        return this.HAufgabes;
    }

    public void setHAufgabes(Set<HAufgabe> HAufgabes) {
        this.HAufgabes = HAufgabes;
    }
    
    @Override
    public boolean equals(Object object) {
        // Basic checks.
        if (object == this) {
            return true;
        }
        if (object == null || getClass() != object.getClass()) {
            return false;
        }

        // Property checks.
        HAuftrag other = (HAuftrag) object;
        if (auftragsnummer == null ? other.auftragsnummer != null : !auftragsnummer.equals(other.auftragsnummer)) {
            return false;
        }
        

        // All passed.
        return true;
    }
}
