package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HAuftragMitarbeiterAssignment generated by hbm2java
 */
@Entity
@Table(name="h_auftrag_mitarbeiter_assignment"
    ,catalog="paulprod"
)
public class HAuftragMitarbeiterAssignment  implements java.io.Serializable {


     private HAuftragMitarbeiterAssignmentId id;
     private Mitarbeiter mitarbeiter;
     private HAuftrag HAuftrag;
     private HSecurityrole HSecurityrole;
     private Integer hid;
     private Date HCreatedat;
     private Integer HCreatedby;
     private Date HModifiedat;
     private Integer HModifiedby;

    public HAuftragMitarbeiterAssignment() {
    }

	
    public HAuftragMitarbeiterAssignment(HAuftragMitarbeiterAssignmentId id, Mitarbeiter mitarbeiter, HAuftrag HAuftrag, HSecurityrole HSecurityrole) {
        this.id = id;
        this.mitarbeiter = mitarbeiter;
        this.HAuftrag = HAuftrag;
        this.HSecurityrole = HSecurityrole;
    }
    public HAuftragMitarbeiterAssignment(HAuftragMitarbeiterAssignmentId id, Mitarbeiter mitarbeiter, HAuftrag HAuftrag, HSecurityrole HSecurityrole, Integer hid, Date HCreatedat, Integer HCreatedby, Date HModifiedat, Integer HModifiedby) {
       this.id = id;
       this.mitarbeiter = mitarbeiter;
       this.HAuftrag = HAuftrag;
       this.HSecurityrole = HSecurityrole;
       this.hid = hid;
       this.HCreatedat = HCreatedat;
       this.HCreatedby = HCreatedby;
       this.HModifiedat = HModifiedat;
       this.HModifiedby = HModifiedby;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="auftrag", column=@Column(name="auftrag", nullable=false) ), 
        @AttributeOverride(name="role", column=@Column(name="role", nullable=false) ), 
        @AttributeOverride(name="mitarbeiterid", column=@Column(name="mitarbeiterid", nullable=false) ) } )
    public HAuftragMitarbeiterAssignmentId getId() {
        return this.id;
    }
    
    public void setId(HAuftragMitarbeiterAssignmentId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mitarbeiterid", nullable=false, insertable=false, updatable=false)
    public Mitarbeiter getMitarbeiter() {
        return this.mitarbeiter;
    }
    
    public void setMitarbeiter(Mitarbeiter mitarbeiter) {
        this.mitarbeiter = mitarbeiter;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="auftrag", nullable=false, insertable=false, updatable=false)
    public HAuftrag getHAuftrag() {
        return this.HAuftrag;
    }
    
    public void setHAuftrag(HAuftrag HAuftrag) {
        this.HAuftrag = HAuftrag;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role", nullable=false, insertable=false, updatable=false)
    public HSecurityrole getHSecurityrole() {
        return this.HSecurityrole;
    }
    
    public void setHSecurityrole(HSecurityrole HSecurityrole) {
        this.HSecurityrole = HSecurityrole;
    }
    
    @Column(name="hid")
    public Integer getHid() {
        return this.hid;
    }
    
    public void setHid(Integer hid) {
        this.hid = hid;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="h_createdat", length=10)
    public Date getHCreatedat() {
        return this.HCreatedat;
    }
    
    public void setHCreatedat(Date HCreatedat) {
        this.HCreatedat = HCreatedat;
    }
    
    @Column(name="h_createdby")
    public Integer getHCreatedby() {
        return this.HCreatedby;
    }
    
    public void setHCreatedby(Integer HCreatedby) {
        this.HCreatedby = HCreatedby;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="h_modifiedat", length=10)
    public Date getHModifiedat() {
        return this.HModifiedat;
    }
    
    public void setHModifiedat(Date HModifiedat) {
        this.HModifiedat = HModifiedat;
    }
    
    @Column(name="h_modifiedby")
    public Integer getHModifiedby() {
        return this.HModifiedby;
    }
    
    public void setHModifiedby(Integer HModifiedby) {
        this.HModifiedby = HModifiedby;
    }




}


