package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HEinsatzplan generated by hbm2java
 */
@Entity
@Table(name="h_einsatzplan"
    ,catalog="paulprod"
)
public class HEinsatzplan  implements java.io.Serializable {


     private int hid;
     private HAufgabe HAufgabe;
     private Mitarbeiter mitarbeiter;
     private Date jahrmonat;
     private Double planaufwand;
     private Double istaufwand;
     private Double faktaufwand;
     private Double rechnungssatz;
     private Double rkist;
     private Double rkfakt;
     private String freigabefakt;
     private Double sachkosten;
     private Double rkplan;
     private Double kostensatz;
     private Date HCreatedat;
     private Integer HCreatedby;
     private Date HModifiedat;
     private Integer HModifiedby;
     private int sync;
     private String rkplanManuell;
     private String rkfaktManuell;

    public HEinsatzplan() {
    }

	
    public HEinsatzplan(int hid, HAufgabe HAufgabe, Mitarbeiter mitarbeiter, int sync, String rkplanManuell, String rkfaktManuell) {
        this.hid = hid;
        this.HAufgabe = HAufgabe;
        this.mitarbeiter = mitarbeiter;
        this.sync = sync;
        this.rkplanManuell = rkplanManuell;
        this.rkfaktManuell = rkfaktManuell;
    }
    public HEinsatzplan(int hid, HAufgabe HAufgabe, Mitarbeiter mitarbeiter, Date jahrmonat, Double planaufwand, Double istaufwand, Double faktaufwand, Double rechnungssatz, Double rkist, Double rkfakt, String freigabefakt, Double sachkosten, Double rkplan, Double kostensatz, Date HCreatedat, Integer HCreatedby, Date HModifiedat, Integer HModifiedby, int sync, String rkplanManuell, String rkfaktManuell) {
       this.hid = hid;
       this.HAufgabe = HAufgabe;
       this.mitarbeiter = mitarbeiter;
       this.jahrmonat = jahrmonat;
       this.planaufwand = planaufwand;
       this.istaufwand = istaufwand;
       this.faktaufwand = faktaufwand;
       this.rechnungssatz = rechnungssatz;
       this.rkist = rkist;
       this.rkfakt = rkfakt;
       this.freigabefakt = freigabefakt;
       this.sachkosten = sachkosten;
       this.rkplan = rkplan;
       this.kostensatz = kostensatz;
       this.HCreatedat = HCreatedat;
       this.HCreatedby = HCreatedby;
       this.HModifiedat = HModifiedat;
       this.HModifiedby = HModifiedby;
       this.sync = sync;
       this.rkplanManuell = rkplanManuell;
       this.rkfaktManuell = rkfaktManuell;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aufgabe", nullable=false)
    public HAufgabe getHAufgabe() {
        return this.HAufgabe;
    }
    
    public void setHAufgabe(HAufgabe HAufgabe) {
        this.HAufgabe = HAufgabe;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mitarbeiter", nullable=false)
    public Mitarbeiter getMitarbeiter() {
        return this.mitarbeiter;
    }
    
    public void setMitarbeiter(Mitarbeiter mitarbeiter) {
        this.mitarbeiter = mitarbeiter;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="jahrmonat", length=10)
    public Date getJahrmonat() {
        return this.jahrmonat;
    }
    
    public void setJahrmonat(Date jahrmonat) {
        this.jahrmonat = jahrmonat;
    }
    
    @Column(name="planaufwand", precision=22, scale=0)
    public Double getPlanaufwand() {
        return this.planaufwand;
    }
    
    public void setPlanaufwand(Double planaufwand) {
        this.planaufwand = planaufwand;
    }
    
    @Column(name="istaufwand", precision=22, scale=0)
    public Double getIstaufwand() {
        return this.istaufwand;
    }
    
    public void setIstaufwand(Double istaufwand) {
        this.istaufwand = istaufwand;
    }
    
    @Column(name="faktaufwand", precision=22, scale=0)
    public Double getFaktaufwand() {
        return this.faktaufwand;
    }
    
    public void setFaktaufwand(Double faktaufwand) {
        this.faktaufwand = faktaufwand;
    }
    
    @Column(name="rechnungssatz", precision=22, scale=0)
    public Double getRechnungssatz() {
        return this.rechnungssatz;
    }
    
    public void setRechnungssatz(Double rechnungssatz) {
        this.rechnungssatz = rechnungssatz;
    }
    
    @Column(name="rkist", precision=22, scale=0)
    public Double getRkist() {
        return this.rkist;
    }
    
    public void setRkist(Double rkist) {
        this.rkist = rkist;
    }
    
    @Column(name="rkfakt", precision=22, scale=0)
    public Double getRkfakt() {
        return this.rkfakt;
    }
    
    public void setRkfakt(Double rkfakt) {
        this.rkfakt = rkfakt;
    }
    
    @Column(name="freigabefakt", length=3)
    public String getFreigabefakt() {
        return this.freigabefakt;
    }
    
    public void setFreigabefakt(String freigabefakt) {
        this.freigabefakt = freigabefakt;
    }
    
    @Column(name="sachkosten", precision=22, scale=0)
    public Double getSachkosten() {
        return this.sachkosten;
    }
    
    public void setSachkosten(Double sachkosten) {
        this.sachkosten = sachkosten;
    }
    
    @Column(name="rkplan", precision=22, scale=0)
    public Double getRkplan() {
        return this.rkplan;
    }
    
    public void setRkplan(Double rkplan) {
        this.rkplan = rkplan;
    }
    
    @Column(name="kostensatz", precision=22, scale=0)
    public Double getKostensatz() {
        return this.kostensatz;
    }
    
    public void setKostensatz(Double kostensatz) {
        this.kostensatz = kostensatz;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="h_createdat", length=10)
    public Date getHCreatedat() {
        return this.HCreatedat;
    }
    
    public void setHCreatedat(Date HCreatedat) {
        this.HCreatedat = HCreatedat;
    }
    
    @Column(name="h_createdby")
    public Integer getHCreatedby() {
        return this.HCreatedby;
    }
    
    public void setHCreatedby(Integer HCreatedby) {
        this.HCreatedby = HCreatedby;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="h_modifiedat", length=10)
    public Date getHModifiedat() {
        return this.HModifiedat;
    }
    
    public void setHModifiedat(Date HModifiedat) {
        this.HModifiedat = HModifiedat;
    }
    
    @Column(name="h_modifiedby")
    public Integer getHModifiedby() {
        return this.HModifiedby;
    }
    
    public void setHModifiedby(Integer HModifiedby) {
        this.HModifiedby = HModifiedby;
    }
    
    @Column(name="sync", nullable=false)
    public int getSync() {
        return this.sync;
    }
    
    public void setSync(int sync) {
        this.sync = sync;
    }
    
    @Column(name="rkplan_manuell", nullable=false, length=3)
    public String getRkplanManuell() {
        return this.rkplanManuell;
    }
    
    public void setRkplanManuell(String rkplanManuell) {
        this.rkplanManuell = rkplanManuell;
    }
    
    @Column(name="rkfakt_manuell", nullable=false, length=3)
    public String getRkfaktManuell() {
        return this.rkfaktManuell;
    }
    
    public void setRkfaktManuell(String rkfaktManuell) {
        this.rkfaktManuell = rkfaktManuell;
    }




}


