package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HEinsatzplanAuditTrail generated by hbm2java
 */
@Entity
@Table(name="h_einsatzplan_audit_trail"
    ,catalog="paulprod"
)
public class HEinsatzplanAuditTrail  implements java.io.Serializable {


     private Integer id;
     private Date auditTrailDatum;
     private int hid;
     private int aufgabe;
     private int mitarbeiter;
     private Date jahrmonat;
     private Double planaufwand;
     private Double istaufwand;
     private Double faktaufwand;
     private Double rechnungssatz;
     private Double rkist;
     private Double rkfakt;
     private String freigabefakt;
     private Double sachkosten;
     private Double rkplan;
     private Double kostensatz;
     private Date HCreatedat;
     private Integer HCreatedby;
     private Date HModifiedat;
     private Integer HModifiedby;

    public HEinsatzplanAuditTrail() {
    }

	
    public HEinsatzplanAuditTrail(int hid, int aufgabe, int mitarbeiter) {
        this.hid = hid;
        this.aufgabe = aufgabe;
        this.mitarbeiter = mitarbeiter;
    }
    public HEinsatzplanAuditTrail(Date auditTrailDatum, int hid, int aufgabe, int mitarbeiter, Date jahrmonat, Double planaufwand, Double istaufwand, Double faktaufwand, Double rechnungssatz, Double rkist, Double rkfakt, String freigabefakt, Double sachkosten, Double rkplan, Double kostensatz, Date HCreatedat, Integer HCreatedby, Date HModifiedat, Integer HModifiedby) {
       this.auditTrailDatum = auditTrailDatum;
       this.hid = hid;
       this.aufgabe = aufgabe;
       this.mitarbeiter = mitarbeiter;
       this.jahrmonat = jahrmonat;
       this.planaufwand = planaufwand;
       this.istaufwand = istaufwand;
       this.faktaufwand = faktaufwand;
       this.rechnungssatz = rechnungssatz;
       this.rkist = rkist;
       this.rkfakt = rkfakt;
       this.freigabefakt = freigabefakt;
       this.sachkosten = sachkosten;
       this.rkplan = rkplan;
       this.kostensatz = kostensatz;
       this.HCreatedat = HCreatedat;
       this.HCreatedby = HCreatedby;
       this.HModifiedat = HModifiedat;
       this.HModifiedby = HModifiedby;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="audit_trail_datum", length=19)
    public Date getAuditTrailDatum() {
        return this.auditTrailDatum;
    }
    
    public void setAuditTrailDatum(Date auditTrailDatum) {
        this.auditTrailDatum = auditTrailDatum;
    }
    
    @Column(name="hid", nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="aufgabe", nullable=false)
    public int getAufgabe() {
        return this.aufgabe;
    }
    
    public void setAufgabe(int aufgabe) {
        this.aufgabe = aufgabe;
    }
    
    @Column(name="mitarbeiter", nullable=false)
    public int getMitarbeiter() {
        return this.mitarbeiter;
    }
    
    public void setMitarbeiter(int mitarbeiter) {
        this.mitarbeiter = mitarbeiter;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="jahrmonat", length=10)
    public Date getJahrmonat() {
        return this.jahrmonat;
    }
    
    public void setJahrmonat(Date jahrmonat) {
        this.jahrmonat = jahrmonat;
    }
    
    @Column(name="planaufwand", precision=22, scale=0)
    public Double getPlanaufwand() {
        return this.planaufwand;
    }
    
    public void setPlanaufwand(Double planaufwand) {
        this.planaufwand = planaufwand;
    }
    
    @Column(name="istaufwand", precision=22, scale=0)
    public Double getIstaufwand() {
        return this.istaufwand;
    }
    
    public void setIstaufwand(Double istaufwand) {
        this.istaufwand = istaufwand;
    }
    
    @Column(name="faktaufwand", precision=22, scale=0)
    public Double getFaktaufwand() {
        return this.faktaufwand;
    }
    
    public void setFaktaufwand(Double faktaufwand) {
        this.faktaufwand = faktaufwand;
    }
    
    @Column(name="rechnungssatz", precision=22, scale=0)
    public Double getRechnungssatz() {
        return this.rechnungssatz;
    }
    
    public void setRechnungssatz(Double rechnungssatz) {
        this.rechnungssatz = rechnungssatz;
    }
    
    @Column(name="rkist", precision=22, scale=0)
    public Double getRkist() {
        return this.rkist;
    }
    
    public void setRkist(Double rkist) {
        this.rkist = rkist;
    }
    
    @Column(name="rkfakt", precision=22, scale=0)
    public Double getRkfakt() {
        return this.rkfakt;
    }
    
    public void setRkfakt(Double rkfakt) {
        this.rkfakt = rkfakt;
    }
    
    @Column(name="freigabefakt", length=3)
    public String getFreigabefakt() {
        return this.freigabefakt;
    }
    
    public void setFreigabefakt(String freigabefakt) {
        this.freigabefakt = freigabefakt;
    }
    
    @Column(name="sachkosten", precision=22, scale=0)
    public Double getSachkosten() {
        return this.sachkosten;
    }
    
    public void setSachkosten(Double sachkosten) {
        this.sachkosten = sachkosten;
    }
    
    @Column(name="rkplan", precision=22, scale=0)
    public Double getRkplan() {
        return this.rkplan;
    }
    
    public void setRkplan(Double rkplan) {
        this.rkplan = rkplan;
    }
    
    @Column(name="kostensatz", precision=22, scale=0)
    public Double getKostensatz() {
        return this.kostensatz;
    }
    
    public void setKostensatz(Double kostensatz) {
        this.kostensatz = kostensatz;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="h_createdat", length=10)
    public Date getHCreatedat() {
        return this.HCreatedat;
    }
    
    public void setHCreatedat(Date HCreatedat) {
        this.HCreatedat = HCreatedat;
    }
    
    @Column(name="h_createdby")
    public Integer getHCreatedby() {
        return this.HCreatedby;
    }
    
    public void setHCreatedby(Integer HCreatedby) {
        this.HCreatedby = HCreatedby;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="h_modifiedat", length=10)
    public Date getHModifiedat() {
        return this.HModifiedat;
    }
    
    public void setHModifiedat(Date HModifiedat) {
        this.HModifiedat = HModifiedat;
    }
    
    @Column(name="h_modifiedby")
    public Integer getHModifiedby() {
        return this.HModifiedby;
    }
    
    public void setHModifiedby(Integer HModifiedby) {
        this.HModifiedby = HModifiedby;
    }




}


