package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HRechnungspositionen generated by hbm2java
 */
@Entity
@Table(name="h_rechnungspositionen"
    ,catalog="paulprod"
)
public class HRechnungspositionen  implements java.io.Serializable {


     private int hid;
     private HZahlplan HZahlplan;
     private Integer einsatzplanid;
     private Integer mitarbeiterid;
     private Double stundentageanzahl;
     private Double abrechnungssatz;
     private Float summe;
     private String positionstext;

    public HRechnungspositionen() {
    }

	
    public HRechnungspositionen(int hid) {
        this.hid = hid;
    }
    public HRechnungspositionen(int hid, HZahlplan HZahlplan, Integer einsatzplanid, Integer mitarbeiterid, Double stundentageanzahl, Double abrechnungssatz, Float summe, String positionstext) {
       this.hid = hid;
       this.HZahlplan = HZahlplan;
       this.einsatzplanid = einsatzplanid;
       this.mitarbeiterid = mitarbeiterid;
       this.stundentageanzahl = stundentageanzahl;
       this.abrechnungssatz = abrechnungssatz;
       this.summe = summe;
       this.positionstext = positionstext;
    }
   
     @Id 
    
    @Column(name="HID", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ZAHLPLANID")
    public HZahlplan getHZahlplan() {
        return this.HZahlplan;
    }
    
    public void setHZahlplan(HZahlplan HZahlplan) {
        this.HZahlplan = HZahlplan;
    }
    
    @Column(name="EINSATZPLANID")
    public Integer getEinsatzplanid() {
        return this.einsatzplanid;
    }
    
    public void setEinsatzplanid(Integer einsatzplanid) {
        this.einsatzplanid = einsatzplanid;
    }
    
    @Column(name="MITARBEITERID")
    public Integer getMitarbeiterid() {
        return this.mitarbeiterid;
    }
    
    public void setMitarbeiterid(Integer mitarbeiterid) {
        this.mitarbeiterid = mitarbeiterid;
    }
    
    @Column(name="STUNDENTAGEANZAHL", precision=22, scale=0)
    public Double getStundentageanzahl() {
        return this.stundentageanzahl;
    }
    
    public void setStundentageanzahl(Double stundentageanzahl) {
        this.stundentageanzahl = stundentageanzahl;
    }
    
    @Column(name="ABRECHNUNGSSATZ", precision=22, scale=0)
    public Double getAbrechnungssatz() {
        return this.abrechnungssatz;
    }
    
    public void setAbrechnungssatz(Double abrechnungssatz) {
        this.abrechnungssatz = abrechnungssatz;
    }
    
    @Column(name="SUMME", precision=12, scale=0)
    public Float getSumme() {
        return this.summe;
    }
    
    public void setSumme(Float summe) {
        this.summe = summe;
    }
    
    @Column(name="POSITIONSTEXT", length=65535)
    public String getPositionstext() {
        return this.positionstext;
    }
    
    public void setPositionstext(String positionstext) {
        this.positionstext = positionstext;
    }




}


