package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HRkImport generated by hbm2java
 */
@Entity
@Table(name="h_rk_import"
    ,catalog="paulprod"
)
public class HRkImport  implements java.io.Serializable {


     private int hid;
     private int employeeNr;
     private String firstName;
     private String lastName;
     private int tripNr;
     private String auftragsNr;
     private String auftragsBez;
     private String status;
     private Date jahrmonat;
     private Date tripBegin;
     private Date tripEnd;
     private double ammount;
     private boolean processed;
     private int importBy;
     private Date importDate;
     private Date importTime;

    public HRkImport() {
    }

	
    public HRkImport(int hid, int employeeNr, String firstName, String lastName, int tripNr, String auftragsNr, String status, Date jahrmonat, Date tripBegin, Date tripEnd, double ammount, boolean processed, int importBy, Date importDate, Date importTime) {
        this.hid = hid;
        this.employeeNr = employeeNr;
        this.firstName = firstName;
        this.lastName = lastName;
        this.tripNr = tripNr;
        this.auftragsNr = auftragsNr;
        this.status = status;
        this.jahrmonat = jahrmonat;
        this.tripBegin = tripBegin;
        this.tripEnd = tripEnd;
        this.ammount = ammount;
        this.processed = processed;
        this.importBy = importBy;
        this.importDate = importDate;
        this.importTime = importTime;
    }
    public HRkImport(int hid, int employeeNr, String firstName, String lastName, int tripNr, String auftragsNr, String auftragsBez, String status, Date jahrmonat, Date tripBegin, Date tripEnd, double ammount, boolean processed, int importBy, Date importDate, Date importTime) {
       this.hid = hid;
       this.employeeNr = employeeNr;
       this.firstName = firstName;
       this.lastName = lastName;
       this.tripNr = tripNr;
       this.auftragsNr = auftragsNr;
       this.auftragsBez = auftragsBez;
       this.status = status;
       this.jahrmonat = jahrmonat;
       this.tripBegin = tripBegin;
       this.tripEnd = tripEnd;
       this.ammount = ammount;
       this.processed = processed;
       this.importBy = importBy;
       this.importDate = importDate;
       this.importTime = importTime;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="employee_nr", nullable=false)
    public int getEmployeeNr() {
        return this.employeeNr;
    }
    
    public void setEmployeeNr(int employeeNr) {
        this.employeeNr = employeeNr;
    }
    
    @Column(name="first_name", nullable=false, length=30)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="last_name", nullable=false, length=30)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="trip_nr", nullable=false)
    public int getTripNr() {
        return this.tripNr;
    }
    
    public void setTripNr(int tripNr) {
        this.tripNr = tripNr;
    }
    
    @Column(name="auftrags_nr", nullable=false, length=50)
    public String getAuftragsNr() {
        return this.auftragsNr;
    }
    
    public void setAuftragsNr(String auftragsNr) {
        this.auftragsNr = auftragsNr;
    }
    
    @Column(name="auftrags_bez")
    public String getAuftragsBez() {
        return this.auftragsBez;
    }
    
    public void setAuftragsBez(String auftragsBez) {
        this.auftragsBez = auftragsBez;
    }
    
    @Column(name="status", nullable=false, length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="jahrmonat", nullable=false, length=10)
    public Date getJahrmonat() {
        return this.jahrmonat;
    }
    
    public void setJahrmonat(Date jahrmonat) {
        this.jahrmonat = jahrmonat;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="trip_begin", nullable=false, length=10)
    public Date getTripBegin() {
        return this.tripBegin;
    }
    
    public void setTripBegin(Date tripBegin) {
        this.tripBegin = tripBegin;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="trip_end", nullable=false, length=10)
    public Date getTripEnd() {
        return this.tripEnd;
    }
    
    public void setTripEnd(Date tripEnd) {
        this.tripEnd = tripEnd;
    }
    
    @Column(name="ammount", nullable=false, precision=22, scale=0)
    public double getAmmount() {
        return this.ammount;
    }
    
    public void setAmmount(double ammount) {
        this.ammount = ammount;
    }
    
    @Column(name="processed", nullable=false)
    public boolean isProcessed() {
        return this.processed;
    }
    
    public void setProcessed(boolean processed) {
        this.processed = processed;
    }
    
    @Column(name="import_by", nullable=false)
    public int getImportBy() {
        return this.importBy;
    }
    
    public void setImportBy(int importBy) {
        this.importBy = importBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="import_date", nullable=false, length=10)
    public Date getImportDate() {
        return this.importDate;
    }
    
    public void setImportDate(Date importDate) {
        this.importDate = importDate;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="import_time", nullable=false, length=8)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }




}


