package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * HRoleInAuftrag generated by hbm2java
 */
@Entity
@Table(name="h_role_in_auftrag"
    ,catalog="paulprod"
)
public class HRoleInAuftrag  implements java.io.Serializable {


     private int hid;
     private String name;
     private String description;
     private Set<HSecurityrole> HSecurityroles = new HashSet<HSecurityrole>(0);

    public HRoleInAuftrag() {
    }

	
    public HRoleInAuftrag(int hid) {
        this.hid = hid;
    }
    public HRoleInAuftrag(int hid, String name, String description, Set<HSecurityrole> HSecurityroles) {
       this.hid = hid;
       this.name = name;
       this.description = description;
       this.HSecurityroles = HSecurityroles;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="h_role_in_auftrag_security_role_assoc", catalog="paulprod", joinColumns = { 
        @JoinColumn(name="roleinauftrag", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="securityrole", nullable=false, updatable=false) })
    public Set<HSecurityrole> getHSecurityroles() {
        return this.HSecurityroles;
    }
    
    public void setHSecurityroles(Set<HSecurityrole> HSecurityroles) {
        this.HSecurityroles = HSecurityroles;
    }




}


