package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * HSecurityright generated by hbm2java
 */
@Entity
@Table(name="h_securityright"
    ,catalog="paulprod"
)
public class HSecurityright  implements java.io.Serializable {


     private int hid;
     private String rightkey;
     private String description;
     private Set<HSecurityrole> HSecurityroles = new HashSet<HSecurityrole>(0);

    public HSecurityright() {
    }

	
    public HSecurityright(int hid) {
        this.hid = hid;
    }
    public HSecurityright(int hid, String rightkey, String description, Set<HSecurityrole> HSecurityroles) {
       this.hid = hid;
       this.rightkey = rightkey;
       this.description = description;
       this.HSecurityroles = HSecurityroles;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="rightkey")
    public String getRightkey() {
        return this.rightkey;
    }
    
    public void setRightkey(String rightkey) {
        this.rightkey = rightkey;
    }
    
    @Column(name="description", length=1024)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="h_securityrole_has_right", catalog="paulprod", joinColumns = { 
        @JoinColumn(name="securityright", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="securityrole", nullable=false, updatable=false) })
    public Set<HSecurityrole> getHSecurityroles() {
        return this.HSecurityroles;
    }
    
    public void setHSecurityroles(Set<HSecurityrole> HSecurityroles) {
        this.HSecurityroles = HSecurityroles;
    }




}


