package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HUseraccountHasUsergroupId generated by hbm2java
 */
@Embeddable
public class HUseraccountHasUsergroupId  implements java.io.Serializable {


     private int useraccount;
     private int usergroup;

    public HUseraccountHasUsergroupId() {
    }

    public HUseraccountHasUsergroupId(int useraccount, int usergroup) {
       this.useraccount = useraccount;
       this.usergroup = usergroup;
    }
   

    @Column(name="useraccount", nullable=false)
    public int getUseraccount() {
        return this.useraccount;
    }
    
    public void setUseraccount(int useraccount) {
        this.useraccount = useraccount;
    }

    @Column(name="usergroup", nullable=false)
    public int getUsergroup() {
        return this.usergroup;
    }
    
    public void setUsergroup(int usergroup) {
        this.usergroup = usergroup;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HUseraccountHasUsergroupId) ) return false;
		 HUseraccountHasUsergroupId castOther = ( HUseraccountHasUsergroupId ) other; 
         
		 return (this.getUseraccount()==castOther.getUseraccount())
 && (this.getUsergroup()==castOther.getUsergroup());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUseraccount();
         result = 37 * result + this.getUsergroup();
         return result;
   }   


}


