package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HUserRoleInAuftragAssoc generated by hbm2java
 */
@Entity
@Table(name="h_user_role_in_auftrag_assoc"
    ,catalog="paulprod"
)
public class HUserRoleInAuftragAssoc  implements java.io.Serializable {


     private int hid;
     private Integer auftrag;
     private Integer user;
     private String role;

    public HUserRoleInAuftragAssoc() {
    }

	
    public HUserRoleInAuftragAssoc(int hid) {
        this.hid = hid;
    }
    public HUserRoleInAuftragAssoc(int hid, Integer auftrag, Integer user, String role) {
       this.hid = hid;
       this.auftrag = auftrag;
       this.user = user;
       this.role = role;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="auftrag")
    public Integer getAuftrag() {
        return this.auftrag;
    }
    
    public void setAuftrag(Integer auftrag) {
        this.auftrag = auftrag;
    }
    
    @Column(name="user")
    public Integer getUser() {
        return this.user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    
    @Column(name="role")
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


