package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HUseraccountHasSecurityroleId generated by hbm2java
 */
@Embeddable
public class HUseraccountHasSecurityroleId  implements java.io.Serializable {


     private int useraccount;
     private int securityrole;

    public HUseraccountHasSecurityroleId() {
    }

    public HUseraccountHasSecurityroleId(int useraccount, int securityrole) {
       this.useraccount = useraccount;
       this.securityrole = securityrole;
    }
   

    @Column(name="useraccount", nullable=false)
    public int getUseraccount() {
        return this.useraccount;
    }
    
    public void setUseraccount(int useraccount) {
        this.useraccount = useraccount;
    }

    @Column(name="securityrole", nullable=false)
    public int getSecurityrole() {
        return this.securityrole;
    }
    
    public void setSecurityrole(int securityrole) {
        this.securityrole = securityrole;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HUseraccountHasSecurityroleId) ) return false;
		 HUseraccountHasSecurityroleId castOther = ( HUseraccountHasSecurityroleId ) other; 
         
		 return (this.getUseraccount()==castOther.getUseraccount())
 && (this.getSecurityrole()==castOther.getSecurityrole());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUseraccount();
         result = 37 * result + this.getSecurityrole();
         return result;
   }   


}


