package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HUseraccountHasSecurityrole generated by hbm2java
 */
@Entity
@Table(name="h_useraccount_has_securityrole"
    ,catalog="paulprod"
)
public class HUseraccountHasSecurityrole  implements java.io.Serializable {


     private HUseraccountHasSecurityroleId id;
     private HSecurityrole HSecurityrole;

    public HUseraccountHasSecurityrole() {
    }

    public HUseraccountHasSecurityrole(HUseraccountHasSecurityroleId id, HSecurityrole HSecurityrole) {
       this.id = id;
       this.HSecurityrole = HSecurityrole;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="useraccount", column=@Column(name="useraccount", nullable=false) ), 
        @AttributeOverride(name="securityrole", column=@Column(name="securityrole", nullable=false) ) } )
    public HUseraccountHasSecurityroleId getId() {
        return this.id;
    }
    
    public void setId(HUseraccountHasSecurityroleId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="securityrole", nullable=false, insertable=false, updatable=false)
    public HSecurityrole getHSecurityrole() {
        return this.HSecurityrole;
    }
    
    public void setHSecurityrole(HSecurityrole HSecurityrole) {
        this.HSecurityrole = HSecurityrole;
    }




}


