package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HUseraccount generated by hbm2java
 */
@Entity
@Table(name="h_useraccount"
    ,catalog="paulprod"
)
public class HUseraccount  implements java.io.Serializable {


     private int hid;
     private Mitarbeiter mitarbeiter;
     private String login;
     private String passwd;
     private Set<HAuftragUserAssignment> HAuftragUserAssignments = new HashSet<HAuftragUserAssignment>(0);

    public HUseraccount() {
    }

	
    public HUseraccount(int hid) {
        this.hid = hid;
    }
    public HUseraccount(int hid, Mitarbeiter mitarbeiter, String login, String passwd, Set<HAuftragUserAssignment> HAuftragUserAssignments) {
       this.hid = hid;
       this.mitarbeiter = mitarbeiter;
       this.login = login;
       this.passwd = passwd;
       this.HAuftragUserAssignments = HAuftragUserAssignments;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mitarbeiter")
    public Mitarbeiter getMitarbeiter() {
        return this.mitarbeiter;
    }
    
    public void setMitarbeiter(Mitarbeiter mitarbeiter) {
        this.mitarbeiter = mitarbeiter;
    }
    
    @Column(name="login")
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="passwd", length=1024)
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="HUseraccount")
    public Set<HAuftragUserAssignment> getHAuftragUserAssignments() {
        return this.HAuftragUserAssignments;
    }
    
    public void setHAuftragUserAssignments(Set<HAuftragUserAssignment> HAuftragUserAssignments) {
        this.HAuftragUserAssignments = HAuftragUserAssignments;
    }




}


