package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HUseraccountHasUsergroup generated by hbm2java
 */
@Entity
@Table(name="h_useraccount_has_usergroup"
    ,catalog="paulprod"
)
public class HUseraccountHasUsergroup  implements java.io.Serializable {


     private HUseraccountHasUsergroupId id;

    public HUseraccountHasUsergroup() {
    }

    public HUseraccountHasUsergroup(HUseraccountHasUsergroupId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="useraccount", column=@Column(name="useraccount", nullable=false) ), 
        @AttributeOverride(name="usergroup", column=@Column(name="usergroup", nullable=false) ) } )
    public HUseraccountHasUsergroupId getId() {
        return this.id;
    }
    
    public void setId(HUseraccountHasUsergroupId id) {
        this.id = id;
    }




}


