package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HZahlplan generated by hbm2java
 */
@Entity
@Table(name="h_zahlplan"
    ,catalog="paulprod"
)
public class HZahlplan  implements java.io.Serializable {


     private int hid;
     private int auftragsnr;
     private Date rechnungsdatum;
     private String rechnungsnummer;
     private Double rechnungsbetrag;
     private String zahlgrund;
     private String freigaberechnung;
     private String gedruckt;
     private Date zeitraumstart;
     private Date zeitraumende;
     private Integer geschaeftspartner;
     private String waehrung;
     private Integer eingegangen;
     private String anschrift;
     private String rechnungsart;
     private double gelGutschrift;
     private Set<HRechnungspositionen> HRechnungspositionens = new HashSet<HRechnungspositionen>(0);

    public HZahlplan() {
    }

	
    public HZahlplan(int hid, int auftragsnr, String freigaberechnung, String gedruckt, double gelGutschrift) {
        this.hid = hid;
        this.auftragsnr = auftragsnr;
        this.freigaberechnung = freigaberechnung;
        this.gedruckt = gedruckt;
        this.gelGutschrift = gelGutschrift;
    }
    public HZahlplan(int hid, int auftragsnr, Date rechnungsdatum, String rechnungsnummer, Double rechnungsbetrag, String zahlgrund, String freigaberechnung, String gedruckt, Date zeitraumstart, Date zeitraumende, Integer geschaeftspartner, String waehrung, Integer eingegangen, String anschrift, String rechnungsart, double gelGutschrift, Set<HRechnungspositionen> HRechnungspositionens) {
       this.hid = hid;
       this.auftragsnr = auftragsnr;
       this.rechnungsdatum = rechnungsdatum;
       this.rechnungsnummer = rechnungsnummer;
       this.rechnungsbetrag = rechnungsbetrag;
       this.zahlgrund = zahlgrund;
       this.freigaberechnung = freigaberechnung;
       this.gedruckt = gedruckt;
       this.zeitraumstart = zeitraumstart;
       this.zeitraumende = zeitraumende;
       this.geschaeftspartner = geschaeftspartner;
       this.waehrung = waehrung;
       this.eingegangen = eingegangen;
       this.anschrift = anschrift;
       this.rechnungsart = rechnungsart;
       this.gelGutschrift = gelGutschrift;
       this.HRechnungspositionens = HRechnungspositionens;
    }
   
     @Id 
    
    @Column(name="HID", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="AUFTRAGSNR", nullable=false)
    public int getAuftragsnr() {
        return this.auftragsnr;
    }
    
    public void setAuftragsnr(int auftragsnr) {
        this.auftragsnr = auftragsnr;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="RECHNUNGSDATUM", length=10)
    public Date getRechnungsdatum() {
        return this.rechnungsdatum;
    }
    
    public void setRechnungsdatum(Date rechnungsdatum) {
        this.rechnungsdatum = rechnungsdatum;
    }
    
    @Column(name="RECHNUNGSNUMMER", length=200)
    public String getRechnungsnummer() {
        return this.rechnungsnummer;
    }
    
    public void setRechnungsnummer(String rechnungsnummer) {
        this.rechnungsnummer = rechnungsnummer;
    }
    
    @Column(name="RECHNUNGSBETRAG", precision=22, scale=0)
    public Double getRechnungsbetrag() {
        return this.rechnungsbetrag;
    }
    
    public void setRechnungsbetrag(Double rechnungsbetrag) {
        this.rechnungsbetrag = rechnungsbetrag;
    }
    
    @Column(name="ZAHLGRUND", length=1000)
    public String getZahlgrund() {
        return this.zahlgrund;
    }
    
    public void setZahlgrund(String zahlgrund) {
        this.zahlgrund = zahlgrund;
    }
    
    @Column(name="FREIGABERECHNUNG", nullable=false, length=3)
    public String getFreigaberechnung() {
        return this.freigaberechnung;
    }
    
    public void setFreigaberechnung(String freigaberechnung) {
        this.freigaberechnung = freigaberechnung;
    }
    
    @Column(name="GEDRUCKT", nullable=false, length=3)
    public String getGedruckt() {
        return this.gedruckt;
    }
    
    public void setGedruckt(String gedruckt) {
        this.gedruckt = gedruckt;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="ZEITRAUMSTART", length=10)
    public Date getZeitraumstart() {
        return this.zeitraumstart;
    }
    
    public void setZeitraumstart(Date zeitraumstart) {
        this.zeitraumstart = zeitraumstart;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="ZEITRAUMENDE", length=10)
    public Date getZeitraumende() {
        return this.zeitraumende;
    }
    
    public void setZeitraumende(Date zeitraumende) {
        this.zeitraumende = zeitraumende;
    }
    
    @Column(name="GESCHAEFTSPARTNER")
    public Integer getGeschaeftspartner() {
        return this.geschaeftspartner;
    }
    
    public void setGeschaeftspartner(Integer geschaeftspartner) {
        this.geschaeftspartner = geschaeftspartner;
    }
    
    @Column(name="waehrung", length=5)
    public String getWaehrung() {
        return this.waehrung;
    }
    
    public void setWaehrung(String waehrung) {
        this.waehrung = waehrung;
    }
    
    @Column(name="eingegangen")
    public Integer getEingegangen() {
        return this.eingegangen;
    }
    
    public void setEingegangen(Integer eingegangen) {
        this.eingegangen = eingegangen;
    }
    
    @Column(name="ANSCHRIFT", length=65535)
    public String getAnschrift() {
        return this.anschrift;
    }
    
    public void setAnschrift(String anschrift) {
        this.anschrift = anschrift;
    }
    
    @Column(name="rechnungsart", length=1)
    public String getRechnungsart() {
        return this.rechnungsart;
    }
    
    public void setRechnungsart(String rechnungsart) {
        this.rechnungsart = rechnungsart;
    }
    
    @Column(name="gel_gutschrift", nullable=false, precision=22, scale=0)
    public double getGelGutschrift() {
        return this.gelGutschrift;
    }
    
    public void setGelGutschrift(double gelGutschrift) {
        this.gelGutschrift = gelGutschrift;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="HZahlplan")
    public Set<HRechnungspositionen> getHRechnungspositionens() {
        return this.HRechnungspositionens;
    }
    
    public void setHRechnungspositionens(Set<HRechnungspositionen> HRechnungspositionens) {
        this.HRechnungspositionens = HRechnungspositionens;
    }




}


