package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HZeiterfassung generated by hbm2java
 */
@Entity
@Table(name="h_zeiterfassung"
    ,catalog="paulprod"
)
public class HZeiterfassung  implements java.io.Serializable {


     private int hid;
     private int mitarbeiter;
     private int aufgabe;
     private Date datum;
     private Date beginn;
     private Date ende;
     private String bemerkung;
     private String reisetaetigkeit;
     private Integer kostenstelle;
     private Double stunden;
     private Double pause;
     private Character bestaetigt;
     private int sync;
     private double istStunden;
     private Integer worklogId;

    public HZeiterfassung() {
    }

	
    public HZeiterfassung(int hid, int mitarbeiter, int aufgabe, Date datum, Date beginn, Date ende, String reisetaetigkeit, int sync, double istStunden) {
        this.hid = hid;
        this.mitarbeiter = mitarbeiter;
        this.aufgabe = aufgabe;
        this.datum = datum;
        this.beginn = beginn;
        this.ende = ende;
        this.reisetaetigkeit = reisetaetigkeit;
        this.sync = sync;
        this.istStunden = istStunden;
    }
    public HZeiterfassung(int hid, int mitarbeiter, int aufgabe, Date datum, Date beginn, Date ende, String bemerkung, String reisetaetigkeit, Integer kostenstelle, Double stunden, Double pause, Character bestaetigt, int sync, double istStunden, Integer worklogId) {
       this.hid = hid;
       this.mitarbeiter = mitarbeiter;
       this.aufgabe = aufgabe;
       this.datum = datum;
       this.beginn = beginn;
       this.ende = ende;
       this.bemerkung = bemerkung;
       this.reisetaetigkeit = reisetaetigkeit;
       this.kostenstelle = kostenstelle;
       this.stunden = stunden;
       this.pause = pause;
       this.bestaetigt = bestaetigt;
       this.sync = sync;
       this.istStunden = istStunden;
       this.worklogId = worklogId;
    }
   
     @Id 
    
    @Column(name="HID", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="MITARBEITER", nullable=false)
    public int getMitarbeiter() {
        return this.mitarbeiter;
    }
    
    public void setMitarbeiter(int mitarbeiter) {
        this.mitarbeiter = mitarbeiter;
    }
    
    @Column(name="AUFGABE", nullable=false)
    public int getAufgabe() {
        return this.aufgabe;
    }
    
    public void setAufgabe(int aufgabe) {
        this.aufgabe = aufgabe;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATUM", nullable=false, length=10)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="BEGINN", nullable=false, length=8)
    public Date getBeginn() {
        return this.beginn;
    }
    
    public void setBeginn(Date beginn) {
        this.beginn = beginn;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="ENDE", nullable=false, length=8)
    public Date getEnde() {
        return this.ende;
    }
    
    public void setEnde(Date ende) {
        this.ende = ende;
    }
    
    @Column(name="BEMERKUNG", length=65535)
    public String getBemerkung() {
        return this.bemerkung;
    }
    
    public void setBemerkung(String bemerkung) {
        this.bemerkung = bemerkung;
    }
    
    @Column(name="REISETAETIGKEIT", nullable=false, length=3)
    public String getReisetaetigkeit() {
        return this.reisetaetigkeit;
    }
    
    public void setReisetaetigkeit(String reisetaetigkeit) {
        this.reisetaetigkeit = reisetaetigkeit;
    }
    
    @Column(name="KOSTENSTELLE")
    public Integer getKostenstelle() {
        return this.kostenstelle;
    }
    
    public void setKostenstelle(Integer kostenstelle) {
        this.kostenstelle = kostenstelle;
    }
    
    @Column(name="stunden", precision=22, scale=0)
    public Double getStunden() {
        return this.stunden;
    }
    
    public void setStunden(Double stunden) {
        this.stunden = stunden;
    }
    
    @Column(name="pause", precision=22, scale=0)
    public Double getPause() {
        return this.pause;
    }
    
    public void setPause(Double pause) {
        this.pause = pause;
    }
    
    @Column(name="bestaetigt", length=1)
    public Character getBestaetigt() {
        return this.bestaetigt;
    }
    
    public void setBestaetigt(Character bestaetigt) {
        this.bestaetigt = bestaetigt;
    }
    
    @Column(name="sync", nullable=false)
    public int getSync() {
        return this.sync;
    }
    
    public void setSync(int sync) {
        this.sync = sync;
    }
    
    @Column(name="ist_stunden", nullable=false, precision=22, scale=0)
    public double getIstStunden() {
        return this.istStunden;
    }
    
    public void setIstStunden(double istStunden) {
        this.istStunden = istStunden;
    }
    
    @Column(name="WorklogId")
    public Integer getWorklogId() {
        return this.worklogId;
    }
    
    public void setWorklogId(Integer worklogId) {
        this.worklogId = worklogId;
    }




}


