package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ImpJira generated by hbm2java
 */
@Entity
@Table(name="imp_jira"
    ,catalog="paulprod"
)
public class ImpJira  implements java.io.Serializable {


     private Integer id;
     private String issue;
     private Double hours;
     private Date workdate;
     private String username;
     private String anr;
     private String knr;
     private String summary;

    public ImpJira() {
    }

    public ImpJira(String issue, Double hours, Date workdate, String username, String anr, String knr, String summary) {
       this.issue = issue;
       this.hours = hours;
       this.workdate = workdate;
       this.username = username;
       this.anr = anr;
       this.knr = knr;
       this.summary = summary;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="issue", length=200)
    public String getIssue() {
        return this.issue;
    }
    
    public void setIssue(String issue) {
        this.issue = issue;
    }
    
    @Column(name="hours", precision=22, scale=0)
    public Double getHours() {
        return this.hours;
    }
    
    public void setHours(Double hours) {
        this.hours = hours;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="workdate", length=10)
    public Date getWorkdate() {
        return this.workdate;
    }
    
    public void setWorkdate(Date workdate) {
        this.workdate = workdate;
    }
    
    @Column(name="username", length=200)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="anr", length=200)
    public String getAnr() {
        return this.anr;
    }
    
    public void setAnr(String anr) {
        this.anr = anr;
    }
    
    @Column(name="knr", length=200)
    public String getKnr() {
        return this.knr;
    }
    
    public void setKnr(String knr) {
        this.knr = knr;
    }
    
    @Column(name="summary", length=200)
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }




}


