package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KondVariabelPos generated by hbm2java
 */
@Entity
@Table(name="kond_variabel_pos"
    ,catalog="paulprod"
)
public class KondVariabelPos  implements java.io.Serializable {


     private Integer hid;
     private int manr;
     private short jahr;
     private String konditionsTyp;
     private String bezeichnung;
     private BigDecimal minWert;
     private BigDecimal maxWert;
     private Float zielbetrag;
     private BigDecimal istwert;
     private Float istbetrag;

    public KondVariabelPos() {
    }

	
    public KondVariabelPos(int manr, short jahr) {
        this.manr = manr;
        this.jahr = jahr;
    }
    public KondVariabelPos(int manr, short jahr, String konditionsTyp, String bezeichnung, BigDecimal minWert, BigDecimal maxWert, Float zielbetrag, BigDecimal istwert, Float istbetrag) {
       this.manr = manr;
       this.jahr = jahr;
       this.konditionsTyp = konditionsTyp;
       this.bezeichnung = bezeichnung;
       this.minWert = minWert;
       this.maxWert = maxWert;
       this.zielbetrag = zielbetrag;
       this.istwert = istwert;
       this.istbetrag = istbetrag;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="hid", unique=true, nullable=false)
    public Integer getHid() {
        return this.hid;
    }
    
    public void setHid(Integer hid) {
        this.hid = hid;
    }
    
    @Column(name="manr", nullable=false)
    public int getManr() {
        return this.manr;
    }
    
    public void setManr(int manr) {
        this.manr = manr;
    }
    
    @Column(name="jahr", nullable=false)
    public short getJahr() {
        return this.jahr;
    }
    
    public void setJahr(short jahr) {
        this.jahr = jahr;
    }
    
    @Column(name="konditions_typ", length=50)
    public String getKonditionsTyp() {
        return this.konditionsTyp;
    }
    
    public void setKonditionsTyp(String konditionsTyp) {
        this.konditionsTyp = konditionsTyp;
    }
    
    @Column(name="bezeichnung", length=50)
    public String getBezeichnung() {
        return this.bezeichnung;
    }
    
    public void setBezeichnung(String bezeichnung) {
        this.bezeichnung = bezeichnung;
    }
    
    @Column(name="min_wert", precision=8)
    public BigDecimal getMinWert() {
        return this.minWert;
    }
    
    public void setMinWert(BigDecimal minWert) {
        this.minWert = minWert;
    }
    
    @Column(name="max_wert", precision=8)
    public BigDecimal getMaxWert() {
        return this.maxWert;
    }
    
    public void setMaxWert(BigDecimal maxWert) {
        this.maxWert = maxWert;
    }
    
    @Column(name="zielbetrag", precision=12, scale=0)
    public Float getZielbetrag() {
        return this.zielbetrag;
    }
    
    public void setZielbetrag(Float zielbetrag) {
        this.zielbetrag = zielbetrag;
    }
    
    @Column(name="istwert", precision=8)
    public BigDecimal getIstwert() {
        return this.istwert;
    }
    
    public void setIstwert(BigDecimal istwert) {
        this.istwert = istwert;
    }
    
    @Column(name="istbetrag", precision=12, scale=0)
    public Float getIstbetrag() {
        return this.istbetrag;
    }
    
    public void setIstbetrag(Float istbetrag) {
        this.istbetrag = istbetrag;
    }




}


