package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * KondGehalt generated by hbm2java
 */
@Entity
@Table(name="kond_gehalt"
    ,catalog="paulprod"
    , uniqueConstraints = @UniqueConstraint(columnNames={"manr", "gültigab"}) 
)
public class KondGehalt  implements java.io.Serializable {


     private Integer hid;
     private Integer manr;
     private Date gültigab;
     private byte status;
     private Float grundgehalt;
     private Byte grundurlaub;
     private Byte wochenstd;
     private Float direktvers;
     private Float kfzanteil;
     private Float sonstanteil;
     private String sonstbez;

    public KondGehalt() {
    }

	
    public KondGehalt(Date gültigab, byte status) {
        this.gültigab = gültigab;
        this.status = status;
    }
    public KondGehalt(Integer manr, Date gültigab, byte status, Float grundgehalt, Byte grundurlaub, Byte wochenstd, Float direktvers, Float kfzanteil, Float sonstanteil, String sonstbez) {
       this.manr = manr;
       this.gültigab = gültigab;
       this.status = status;
       this.grundgehalt = grundgehalt;
       this.grundurlaub = grundurlaub;
       this.wochenstd = wochenstd;
       this.direktvers = direktvers;
       this.kfzanteil = kfzanteil;
       this.sonstanteil = sonstanteil;
       this.sonstbez = sonstbez;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="hid", unique=true, nullable=false)
    public Integer getHid() {
        return this.hid;
    }
    
    public void setHid(Integer hid) {
        this.hid = hid;
    }
    
    @Column(name="manr")
    public Integer getManr() {
        return this.manr;
    }
    
    public void setManr(Integer manr) {
        this.manr = manr;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="gültigab", nullable=false, length=10)
    public Date getGültigab() {
        return this.gültigab;
    }
    
    public void setGültigab(Date gültigab) {
        this.gültigab = gültigab;
    }
    
    @Column(name="status", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    
    @Column(name="grundgehalt", precision=12, scale=0)
    public Float getGrundgehalt() {
        return this.grundgehalt;
    }
    
    public void setGrundgehalt(Float grundgehalt) {
        this.grundgehalt = grundgehalt;
    }
    
    @Column(name="grundurlaub")
    public Byte getGrundurlaub() {
        return this.grundurlaub;
    }
    
    public void setGrundurlaub(Byte grundurlaub) {
        this.grundurlaub = grundurlaub;
    }
    
    @Column(name="wochenstd")
    public Byte getWochenstd() {
        return this.wochenstd;
    }
    
    public void setWochenstd(Byte wochenstd) {
        this.wochenstd = wochenstd;
    }
    
    @Column(name="direktvers", precision=12, scale=0)
    public Float getDirektvers() {
        return this.direktvers;
    }
    
    public void setDirektvers(Float direktvers) {
        this.direktvers = direktvers;
    }
    
    @Column(name="kfzanteil", precision=12, scale=0)
    public Float getKfzanteil() {
        return this.kfzanteil;
    }
    
    public void setKfzanteil(Float kfzanteil) {
        this.kfzanteil = kfzanteil;
    }
    
    @Column(name="sonstanteil", precision=12, scale=0)
    public Float getSonstanteil() {
        return this.sonstanteil;
    }
    
    public void setSonstanteil(Float sonstanteil) {
        this.sonstanteil = sonstanteil;
    }
    
    @Column(name="sonstbez", length=25)
    public String getSonstbez() {
        return this.sonstbez;
    }
    
    public void setSonstbez(String sonstbez) {
        this.sonstbez = sonstbez;
    }




}


