package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * KondSozVers generated by hbm2java
 */
@Entity
@Table(name="kond_soz_vers"
    ,catalog="paulprod"
    , uniqueConstraints = @UniqueConstraint(columnNames={"manr", "gültigab"}) 
)
public class KondSozVers  implements java.io.Serializable {


     private Integer hid;
     private Integer manr;
     private Date gültigab;
     private Float rv;
     private Float av;
     private Float kv;
     private String kasse;
     private Character privat;
     private Float pv;
     private Float aok;

    public KondSozVers() {
    }

    public KondSozVers(Integer manr, Date gültigab, Float rv, Float av, Float kv, String kasse, Character privat, Float pv, Float aok) {
       this.manr = manr;
       this.gültigab = gültigab;
       this.rv = rv;
       this.av = av;
       this.kv = kv;
       this.kasse = kasse;
       this.privat = privat;
       this.pv = pv;
       this.aok = aok;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="hid", unique=true, nullable=false)
    public Integer getHid() {
        return this.hid;
    }
    
    public void setHid(Integer hid) {
        this.hid = hid;
    }
    
    @Column(name="manr")
    public Integer getManr() {
        return this.manr;
    }
    
    public void setManr(Integer manr) {
        this.manr = manr;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="gültigab", length=10)
    public Date getGültigab() {
        return this.gültigab;
    }
    
    public void setGültigab(Date gültigab) {
        this.gültigab = gültigab;
    }
    
    @Column(name="rv", precision=12, scale=0)
    public Float getRv() {
        return this.rv;
    }
    
    public void setRv(Float rv) {
        this.rv = rv;
    }
    
    @Column(name="av", precision=12, scale=0)
    public Float getAv() {
        return this.av;
    }
    
    public void setAv(Float av) {
        this.av = av;
    }
    
    @Column(name="kv", precision=12, scale=0)
    public Float getKv() {
        return this.kv;
    }
    
    public void setKv(Float kv) {
        this.kv = kv;
    }
    
    @Column(name="kasse", length=50)
    public String getKasse() {
        return this.kasse;
    }
    
    public void setKasse(String kasse) {
        this.kasse = kasse;
    }
    
    @Column(name="privat", length=1)
    public Character getPrivat() {
        return this.privat;
    }
    
    public void setPrivat(Character privat) {
        this.privat = privat;
    }
    
    @Column(name="pv", precision=12, scale=0)
    public Float getPv() {
        return this.pv;
    }
    
    public void setPv(Float pv) {
        this.pv = pv;
    }
    
    @Column(name="aok", precision=12, scale=0)
    public Float getAok() {
        return this.aok;
    }
    
    public void setAok(Float aok) {
        this.aok = aok;
    }




}


