package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * KondHonorar generated by hbm2java
 */
@Entity
@Table(name="kond_honorar"
    ,catalog="paulprod"
    , uniqueConstraints = @UniqueConstraint(columnNames={"manr", "g�ltigab"}) 
)
public class KondHonorar  implements java.io.Serializable {


     private Integer hid;
     private Integer manr;
     private Date gültigab;
     private byte status;
     private Float tagessatz;
     private Float stundensatz;
     private Float rksatz;
     private Float provision;
     private Short bestellmenge;
     private String einzelvertrag;
     private Date gültigbis;
     private String bemerkung;

    public KondHonorar() {
    }

	
    public KondHonorar(Date gültigab, byte status, String einzelvertrag) {
        this.gültigab = gültigab;
        this.status = status;
        this.einzelvertrag = einzelvertrag;
    }
    public KondHonorar(Integer manr, Date gültigab, byte status, Float tagessatz, Float stundensatz, Float rksatz, Float provision, Short bestellmenge, String einzelvertrag, Date gültigbis, String bemerkung) {
       this.manr = manr;
       this.gültigab = gültigab;
       this.status = status;
       this.tagessatz = tagessatz;
       this.stundensatz = stundensatz;
       this.rksatz = rksatz;
       this.provision = provision;
       this.bestellmenge = bestellmenge;
       this.einzelvertrag = einzelvertrag;
       this.gültigbis = gültigbis;
       this.bemerkung = bemerkung;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="hid", unique=true, nullable=false)
    public Integer getHid() {
        return this.hid;
    }
    
    public void setHid(Integer hid) {
        this.hid = hid;
    }
    
    @Column(name="manr")
    public Integer getManr() {
        return this.manr;
    }
    
    public void setManr(Integer manr) {
        this.manr = manr;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="g�ltigab", nullable=false, length=10)
    public Date getGültigab() {
        return this.gültigab;
    }
    
    public void setGültigab(Date gültigab) {
        this.gültigab = gültigab;
    }
    
    @Column(name="status", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    
    @Column(name="tagessatz", precision=12, scale=0)
    public Float getTagessatz() {
        return this.tagessatz;
    }
    
    public void setTagessatz(Float tagessatz) {
        this.tagessatz = tagessatz;
    }
    
    @Column(name="stundensatz", precision=12, scale=0)
    public Float getStundensatz() {
        return this.stundensatz;
    }
    
    public void setStundensatz(Float stundensatz) {
        this.stundensatz = stundensatz;
    }
    
    @Column(name="rksatz", precision=12, scale=0)
    public Float getRksatz() {
        return this.rksatz;
    }
    
    public void setRksatz(Float rksatz) {
        this.rksatz = rksatz;
    }
    
    @Column(name="provision", precision=12, scale=0)
    public Float getProvision() {
        return this.provision;
    }
    
    public void setProvision(Float provision) {
        this.provision = provision;
    }
    
    @Column(name="bestellmenge")
    public Short getBestellmenge() {
        return this.bestellmenge;
    }
    
    public void setBestellmenge(Short bestellmenge) {
        this.bestellmenge = bestellmenge;
    }
    
    @Column(name="einzelvertrag", nullable=false, length=20)
    public String getEinzelvertrag() {
        return this.einzelvertrag;
    }
    
    public void setEinzelvertrag(String einzelvertrag) {
        this.einzelvertrag = einzelvertrag;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="gültigbis", length=10)
    public Date getGültigbis() {
        return this.gültigbis;
    }
    
    public void setGültigbis(Date gültigbis) {
        this.gültigbis = gültigbis;
    }
    
    @Column(name="bemerkung", length=65535)
    public String getBemerkung() {
        return this.bemerkung;
    }
    
    public void setBemerkung(String bemerkung) {
        this.bemerkung = bemerkung;
    }




}


