package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KondDwId generated by hbm2java
 */
@Embeddable
public class KondDwId  implements java.io.Serializable {


     private int hid;
     private String kfzKz;

    public KondDwId() {
    }

    public KondDwId(int hid, String kfzKz) {
       this.hid = hid;
       this.kfzKz = kfzKz;
    }
   

    @Column(name="hid", nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }

    @Column(name="kfz_kz", nullable=false, length=20)
    public String getKfzKz() {
        return this.kfzKz;
    }
    
    public void setKfzKz(String kfzKz) {
        this.kfzKz = kfzKz;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KondDwId) ) return false;
		 KondDwId castOther = ( KondDwId ) other; 
         
		 return (this.getHid()==castOther.getHid())
 && ( (this.getKfzKz()==castOther.getKfzKz()) || ( this.getKfzKz()!=null && castOther.getKfzKz()!=null && this.getKfzKz().equals(castOther.getKfzKz()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHid();
         result = 37 * result + ( getKfzKz() == null ? 0 : this.getKfzKz().hashCode() );
         return result;
   }   


}


