package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KondDw generated by hbm2java
 */
@Entity
@Table(name="kond_dw"
    ,catalog="paulprod"
)
public class KondDw  implements java.io.Serializable {


     private KondDwId id;
     private Integer manr;
     private String kfzTyp;
     private Float verbrauch;
     private Float verbrauchKst;
     private Float kmJahr;
     private Float kmPrivat;
     private String bemerkung;
     private String eigentümer;
     private Date gültigab;
     private Date gültigbis;
     private String vertragsbez;
     private Float kfzKst;
     private Float kstSteuer;
     private Float kstVers;
     private Float sonstKst;

    public KondDw() {
    }

	
    public KondDw(KondDwId id) {
        this.id = id;
    }
    public KondDw(KondDwId id, Integer manr, String kfzTyp, Float verbrauch, Float verbrauchKst, Float kmJahr, Float kmPrivat, String bemerkung, String eigentümer, Date gültigab, Date gültigbis, String vertragsbez, Float kfzKst, Float kstSteuer, Float kstVers, Float sonstKst) {
       this.id = id;
       this.manr = manr;
       this.kfzTyp = kfzTyp;
       this.verbrauch = verbrauch;
       this.verbrauchKst = verbrauchKst;
       this.kmJahr = kmJahr;
       this.kmPrivat = kmPrivat;
       this.bemerkung = bemerkung;
       this.eigentümer = eigentümer;
       this.gültigab = gültigab;
       this.gültigbis = gültigbis;
       this.vertragsbez = vertragsbez;
       this.kfzKst = kfzKst;
       this.kstSteuer = kstSteuer;
       this.kstVers = kstVers;
       this.sonstKst = sonstKst;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="hid", column=@Column(name="hid", nullable=false) ), 
        @AttributeOverride(name="kfzKz", column=@Column(name="kfz_kz", nullable=false, length=20) ) } )
    public KondDwId getId() {
        return this.id;
    }
    
    public void setId(KondDwId id) {
        this.id = id;
    }
    
    @Column(name="manr")
    public Integer getManr() {
        return this.manr;
    }
    
    public void setManr(Integer manr) {
        this.manr = manr;
    }
    
    @Column(name="kfz_typ", length=25)
    public String getKfzTyp() {
        return this.kfzTyp;
    }
    
    public void setKfzTyp(String kfzTyp) {
        this.kfzTyp = kfzTyp;
    }
    
    @Column(name="verbrauch", precision=12, scale=0)
    public Float getVerbrauch() {
        return this.verbrauch;
    }
    
    public void setVerbrauch(Float verbrauch) {
        this.verbrauch = verbrauch;
    }
    
    @Column(name="verbrauch_kst", precision=12, scale=0)
    public Float getVerbrauchKst() {
        return this.verbrauchKst;
    }
    
    public void setVerbrauchKst(Float verbrauchKst) {
        this.verbrauchKst = verbrauchKst;
    }
    
    @Column(name="km_jahr", precision=12, scale=0)
    public Float getKmJahr() {
        return this.kmJahr;
    }
    
    public void setKmJahr(Float kmJahr) {
        this.kmJahr = kmJahr;
    }
    
    @Column(name="km_privat", precision=12, scale=0)
    public Float getKmPrivat() {
        return this.kmPrivat;
    }
    
    public void setKmPrivat(Float kmPrivat) {
        this.kmPrivat = kmPrivat;
    }
    
    @Column(name="bemerkung", length=65535)
    public String getBemerkung() {
        return this.bemerkung;
    }
    
    public void setBemerkung(String bemerkung) {
        this.bemerkung = bemerkung;
    }
    
    @Column(name="eigent�mer", length=25)
    public String getEigentümer() {
        return this.eigentümer;
    }
    
    public void setEigentümer(String eigentümer) {
        this.eigentümer = eigentümer;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="gültigab", length=10)
    public Date getGültigab() {
        return this.gültigab;
    }
    
    public void setGültigab(Date gültigab) {
        this.gültigab = gültigab;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="gültigbis", length=10)
    public Date getGültigbis() {
        return this.gültigbis;
    }
    
    public void setGültigbis(Date gültigbis) {
        this.gültigbis = gültigbis;
    }
    
    @Column(name="vertragsbez", length=25)
    public String getVertragsbez() {
        return this.vertragsbez;
    }
    
    public void setVertragsbez(String vertragsbez) {
        this.vertragsbez = vertragsbez;
    }
    
    @Column(name="kfz_kst", precision=12, scale=0)
    public Float getKfzKst() {
        return this.kfzKst;
    }
    
    public void setKfzKst(Float kfzKst) {
        this.kfzKst = kfzKst;
    }
    
    @Column(name="kst_steuer", precision=12, scale=0)
    public Float getKstSteuer() {
        return this.kstSteuer;
    }
    
    public void setKstSteuer(Float kstSteuer) {
        this.kstSteuer = kstSteuer;
    }
    
    @Column(name="kst_vers", precision=12, scale=0)
    public Float getKstVers() {
        return this.kstVers;
    }
    
    public void setKstVers(Float kstVers) {
        this.kstVers = kstVers;
    }
    
    @Column(name="sonst_kst", precision=12, scale=0)
    public Float getSonstKst() {
        return this.sonstKst;
    }
    
    public void setSonstKst(Float sonstKst) {
        this.sonstKst = sonstKst;
    }




}


