package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * KondJahr generated by hbm2java
 */
@Entity
@Table(name="kond_jahr"
    ,catalog="paulprod"
    , uniqueConstraints = @UniqueConstraint(columnNames={"manr", "jahr"}) 
)
public class KondJahr  implements java.io.Serializable {


     private Integer hid;
     private int manr;
     private short jahr;
     private Float ausgezahlt;

    public KondJahr() {
    }

	
    public KondJahr(int manr, short jahr) {
        this.manr = manr;
        this.jahr = jahr;
    }
    public KondJahr(int manr, short jahr, Float ausgezahlt) {
       this.manr = manr;
       this.jahr = jahr;
       this.ausgezahlt = ausgezahlt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="hid", unique=true, nullable=false)
    public Integer getHid() {
        return this.hid;
    }
    
    public void setHid(Integer hid) {
        this.hid = hid;
    }
    
    @Column(name="manr", nullable=false)
    public int getManr() {
        return this.manr;
    }
    
    public void setManr(int manr) {
        this.manr = manr;
    }
    
    @Column(name="jahr", nullable=false)
    public short getJahr() {
        return this.jahr;
    }
    
    public void setJahr(short jahr) {
        this.jahr = jahr;
    }
    
    @Column(name="ausgezahlt", precision=12, scale=0)
    public Float getAusgezahlt() {
        return this.ausgezahlt;
    }
    
    public void setAusgezahlt(Float ausgezahlt) {
        this.ausgezahlt = ausgezahlt;
    }




}


