package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kostenstelle generated by hbm2java
 */
@Entity
@Table(name="kostenstelle"
    ,catalog="paulprod"
)
public class Kostenstelle  implements java.io.Serializable {


     private int hid;
     private String kstname;
     private Integer verantwortlich;
     private int gesellschaft;
     private String kstnummer;
     private String active;
     private String freigabebuchung;
     private Set<HAuftrag> HAuftrags = new HashSet<HAuftrag>(0);

    public Kostenstelle() {
    }

	
    public Kostenstelle(int hid, int gesellschaft, String active, String freigabebuchung) {
        this.hid = hid;
        this.gesellschaft = gesellschaft;
        this.active = active;
        this.freigabebuchung = freigabebuchung;
    }
    public Kostenstelle(int hid, String kstname, Integer verantwortlich, int gesellschaft, String kstnummer, String active, String freigabebuchung, Set<HAuftrag> HAuftrags) {
       this.hid = hid;
       this.kstname = kstname;
       this.verantwortlich = verantwortlich;
       this.gesellschaft = gesellschaft;
       this.kstnummer = kstnummer;
       this.active = active;
       this.freigabebuchung = freigabebuchung;
       this.HAuftrags = HAuftrags;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="kstname")
    public String getKstname() {
        return this.kstname;
    }
    
    public void setKstname(String kstname) {
        this.kstname = kstname;
    }
    
    @Column(name="verantwortlich")
    public Integer getVerantwortlich() {
        return this.verantwortlich;
    }
    
    public void setVerantwortlich(Integer verantwortlich) {
        this.verantwortlich = verantwortlich;
    }
    
    @Column(name="gesellschaft", nullable=false)
    public int getGesellschaft() {
        return this.gesellschaft;
    }
    
    public void setGesellschaft(int gesellschaft) {
        this.gesellschaft = gesellschaft;
    }
    
    @Column(name="kstnummer")
    public String getKstnummer() {
        return this.kstnummer;
    }
    
    public void setKstnummer(String kstnummer) {
        this.kstnummer = kstnummer;
    }
    
    @Column(name="active", nullable=false, length=1)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    
    @Column(name="freigabebuchung", nullable=false, length=1)
    public String getFreigabebuchung() {
        return this.freigabebuchung;
    }
    
    public void setFreigabebuchung(String freigabebuchung) {
        this.freigabebuchung = freigabebuchung;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="kostenstelle")
    public Set<HAuftrag> getHAuftrags() {
        return this.HAuftrags;
    }
    
    public void setHAuftrags(Set<HAuftrag> HAuftrags) {
        this.HAuftrags = HAuftrags;
    }




}


