package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kundengruppe generated by hbm2java
 */
@Entity
@Table(name="kundengruppe"
    ,catalog="paulprod"
)
public class Kundengruppe  implements java.io.Serializable {


     private int hid;
     private String name;
     private String bemerkungen;
     private String active;
     private Set<Gp> gps = new HashSet<Gp>(0);

    public Kundengruppe() {
    }

	
    public Kundengruppe(int hid, String active) {
        this.hid = hid;
        this.active = active;
    }
    public Kundengruppe(int hid, String name, String bemerkungen, String active, Set<Gp> gps) {
       this.hid = hid;
       this.name = name;
       this.bemerkungen = bemerkungen;
       this.active = active;
       this.gps = gps;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="bemerkungen", length=65535)
    public String getBemerkungen() {
        return this.bemerkungen;
    }
    
    public void setBemerkungen(String bemerkungen) {
        this.bemerkungen = bemerkungen;
    }
    
    @Column(name="active", nullable=false, length=1)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="kundengruppe")
    public Set<Gp> getGps() {
        return this.gps;
    }
    
    public void setGps(Set<Gp> gps) {
        this.gps = gps;
    }




}


