package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Leistungseinheit generated by hbm2java
 */
@Entity
@Table(name="leistungseinheit"
    ,catalog="paulprod"
)
public class Leistungseinheit  implements java.io.Serializable {


     private int hid;
     private String name;
     private String abrechnungsart;

    public Leistungseinheit() {
    }

    public Leistungseinheit(int hid, String name, String abrechnungsart) {
       this.hid = hid;
       this.name = name;
       this.abrechnungsart = abrechnungsart;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="abrechnungsart", nullable=false, length=8)
    public String getAbrechnungsart() {
        return this.abrechnungsart;
    }
    
    public void setAbrechnungsart(String abrechnungsart) {
        this.abrechnungsart = abrechnungsart;
    }




}


