package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LeSpalte generated by hbm2java
 */
@Entity
@Table(name="le_spalte"
    ,catalog="paulprod"
)
public class LeSpalte  implements java.io.Serializable {


     private int hid;
     private float value;

    public LeSpalte() {
    }

    public LeSpalte(int hid, float value) {
       this.hid = hid;
       this.value = value;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="value", nullable=false, precision=12, scale=0)
    public float getValue() {
        return this.value;
    }
    
    public void setValue(float value) {
        this.value = value;
    }




}


