package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LeWert generated by hbm2java
 */
@Entity
@Table(name="le_wert"
    ,catalog="paulprod"
)
public class LeWert  implements java.io.Serializable {


     private int hid;
     private int leistungseinheit;
     private int minMaxLe;
     private int leSpalte;
     private Double value;

    public LeWert() {
    }

	
    public LeWert(int hid, int leistungseinheit, int minMaxLe, int leSpalte) {
        this.hid = hid;
        this.leistungseinheit = leistungseinheit;
        this.minMaxLe = minMaxLe;
        this.leSpalte = leSpalte;
    }
    public LeWert(int hid, int leistungseinheit, int minMaxLe, int leSpalte, Double value) {
       this.hid = hid;
       this.leistungseinheit = leistungseinheit;
       this.minMaxLe = minMaxLe;
       this.leSpalte = leSpalte;
       this.value = value;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="leistungseinheit", nullable=false)
    public int getLeistungseinheit() {
        return this.leistungseinheit;
    }
    
    public void setLeistungseinheit(int leistungseinheit) {
        this.leistungseinheit = leistungseinheit;
    }
    
    @Column(name="min_max_le", nullable=false)
    public int getMinMaxLe() {
        return this.minMaxLe;
    }
    
    public void setMinMaxLe(int minMaxLe) {
        this.minMaxLe = minMaxLe;
    }
    
    @Column(name="le_spalte", nullable=false)
    public int getLeSpalte() {
        return this.leSpalte;
    }
    
    public void setLeSpalte(int leSpalte) {
        this.leSpalte = leSpalte;
    }
    
    @Column(name="value", precision=22, scale=0)
    public Double getValue() {
        return this.value;
    }
    
    public void setValue(Double value) {
        this.value = value;
    }




}


