package de.affinis.pauline.hbm;
// Generated 17.07.2013 21:19:08 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PQAction generated by hbm2java
 */
@Entity
@Table(name="p_massnahme"
    ,catalog="paulprod"
)
public class PMassnahme  implements java.io.Serializable {


     private Integer hid;
     private Mitarbeiter mitarbeiter;
     private PQKriterium PQKriterium;
     private PUseraccount PUseraccountByModifiedby;
     private PUseraccount PUseraccountByCreatedby;
     private String beschreibung;
     private Date duedate;
     private Date createdat;
     private Date modifiedat;
     private String hinweis;

    public PMassnahme() {
    }

	
    public PMassnahme(Mitarbeiter mitarbeiter, PQKriterium PQKriterium) {
        this.mitarbeiter = mitarbeiter;
        this.PQKriterium = PQKriterium;
    }
    public PMassnahme(Mitarbeiter mitarbeiter, PQKriterium PQKriterium, PUseraccount PUseraccountByModifiedby, PUseraccount PUseraccountByCreatedby, String beschreibung, Date duedate, Date createdat, Date modifiedat, String hinweis) {
       this.mitarbeiter = mitarbeiter;
       this.PQKriterium = PQKriterium;
       this.PUseraccountByModifiedby = PUseraccountByModifiedby;
       this.PUseraccountByCreatedby = PUseraccountByCreatedby;
       this.beschreibung = beschreibung;
       this.duedate = duedate;
       this.createdat = createdat;
       this.modifiedat = modifiedat;
       this.hinweis = hinweis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="hid", unique=true, nullable=false)
    public Integer getHid() {
        return this.hid;
    }
    
    public void setHid(Integer hid) {
        this.hid = hid;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="verantwortlicher", nullable=false)
    public Mitarbeiter getMitarbeiter() {
        return this.mitarbeiter;
    }
    
    public void setMitarbeiter(Mitarbeiter mitarbeiter) {
        this.mitarbeiter = mitarbeiter;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="q_kriterium", nullable=false)
    public PQKriterium getPQKriterium() {
        return this.PQKriterium;
    }
    
    public void setPQKriterium(PQKriterium PQKriterium) {
        this.PQKriterium = PQKriterium;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="modifiedby")
    public PUseraccount getPUseraccountByModifiedby() {
        return this.PUseraccountByModifiedby;
    }
    
    public void setPUseraccountByModifiedby(PUseraccount PUseraccountByModifiedby) {
        this.PUseraccountByModifiedby = PUseraccountByModifiedby;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="createdby")
    public PUseraccount getPUseraccountByCreatedby() {
        return this.PUseraccountByCreatedby;
    }
    
    public void setPUseraccountByCreatedby(PUseraccount PUseraccountByCreatedby) {
        this.PUseraccountByCreatedby = PUseraccountByCreatedby;
    }
    
    @Column(name="beschreibung")
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="duedate", length=10)
    public Date getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdat", length=19)
    public Date getCreatedat() {
        return this.createdat;
    }
    
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifiedat", length=19)
    public Date getModifiedat() {
        return this.modifiedat;
    }
    
    public void setModifiedat(Date modifiedat) {
        this.modifiedat = modifiedat;
    }
    
    @Column(name="hinweis", length=65535)
    public String getHinweis() {
        return this.hinweis;
    }
    
    public void setHinweis(String hinweis) {
        this.hinweis = hinweis;
    }




}


