package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "p_q_objekt_vorlage", catalog = "paulprod")
public class PQObjektVorlage implements java.io.Serializable {

    private Short hid;
    private String name;
    private Set<PQObjekt> PQObjekte = new HashSet<PQObjekt>(0);
    private Set<PQKriterienVorlage> PQKriterienVorlages = new HashSet<PQKriterienVorlage>(0);


    public PQObjektVorlage() {
    }

    public PQObjektVorlage(String name) {
        this.name = name;
    }
    
    public PQObjektVorlage(String name, HashSet<PQObjekt> PQObjekte) {
        this.name = name;
        this.PQObjekte = PQObjekte;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "hid", unique = true, nullable = false)
    public Short getHid() {
        return this.hid;
    }

    public void setHid(Short hid) {
        this.hid = hid;
    }

    @Column(name = "name", nullable=false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="PQObjektVorlage")
    public Set<PQObjekt> getPQObjekte() {
        return this.PQObjekte;
    }
    
    public void setPQObjekte(Set<PQObjekt> PQObjekte) {
        this.PQObjekte = PQObjekte;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="PQObjektVorlage")
    public Set<PQKriterienVorlage> getPQKriterienVorlages() {
        return PQKriterienVorlages;
    }

    public void setPQKriterienVorlages(Set<PQKriterienVorlage> PQKriterienVorlages) {
        this.PQKriterienVorlages = PQKriterienVorlages;
    }
    
    
    @Override
    public boolean equals(Object object) {
        // Basic checks.
        if (object == this) {
            return true;
        }
        if (object == null || getClass() != object.getClass()) {
            return false;
        }

        // Property checks.
        PQObjektVorlage other = (PQObjektVorlage) object;
        if (name == null ? other.name != null : !name.equals(other.name)) {
            return false;
        }


        // All passed.
        return true;
    }
}
