package de.affinis.pauline.hbm;
// Generated 17.07.2013 21:19:08 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * PQObjekt generated by hbm2java
 */
@Entity
@Table(name = "p_q_objekt", catalog = "paulprod")
public class PQObjekt implements java.io.Serializable {

    private Integer hid;
    private HAufgabe HAufgabe;
    private PQProjekt PQProjekt;
    private PUseraccount PUseraccountByModifiedby;
    private PUseraccount PUseraccountByCreatedby;
    private PQObjektVorlage PQObjektVorlage;
    private String name;
    private String beschreibung;
    private BigDecimal QObjektBewertung;
    private BigDecimal QObjektGewichtung;
    private Date createdat;
    private Date modifiedat;
    private String hinweis;
    private Set<PQKriterium> PQKriterien = new HashSet<PQKriterium>(0);
    private List<PQKriterium> KriteriumList = new LinkedList<PQKriterium>();
    private Date evaldat;
    private PStatus PStatus;

    public PQObjekt() {
    }

    public PQObjekt(PQProjekt PQProjekt, PUseraccount PUseraccountByModifiedby, PUseraccount PUseraccountByCreatedby, PQObjektVorlage PQObjektVorlage) {
        this.PQProjekt = PQProjekt;
        this.PUseraccountByModifiedby = PUseraccountByModifiedby;
        this.PUseraccountByCreatedby = PUseraccountByCreatedby;
        this.PQObjektVorlage = PQObjektVorlage;
    }

    public PQObjekt(HAufgabe HAufgabe, PQProjekt PQProjekt, PUseraccount PUseraccountByModifiedby, PUseraccount PUseraccountByCreatedby, PQObjektVorlage PQObjektVorlage, String name, String beschreibung, BigDecimal QObjektBewertung, BigDecimal QObjektGewichtung, Date createdat, Date modifiedat, String hinweis, Set<PQKriterium> PQKriterien, Date evaldat, PStatus PStatus) {
        this.HAufgabe = HAufgabe;
        this.PQProjekt = PQProjekt;
        this.PUseraccountByModifiedby = PUseraccountByModifiedby;
        this.PUseraccountByCreatedby = PUseraccountByCreatedby;
        this.PQObjektVorlage = PQObjektVorlage;
        this.name = name;
        this.beschreibung = beschreibung;
        this.QObjektBewertung = QObjektBewertung;
        this.QObjektGewichtung = QObjektGewichtung;
        this.createdat = createdat;
        this.modifiedat = modifiedat;
        this.hinweis = hinweis;
        this.PQKriterien = PQKriterien;
        this.evaldat = evaldat;
        this.PStatus = PStatus;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "hid", unique = true, nullable = false)
    public Integer getHid() {
        return this.hid;
    }

    public void setHid(Integer hid) {
        this.hid = hid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "aufgabe")
    public HAufgabe getHAufgabe() {
        return this.HAufgabe;
    }

    public void setHAufgabe(HAufgabe HAufgabe) {
        this.HAufgabe = HAufgabe;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "q_projekt", nullable = false)
    public PQProjekt getPQProjekt() {
        return this.PQProjekt;
    }

    public void setPQProjekt(PQProjekt PQProjekt) {
        this.PQProjekt = PQProjekt;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "modifiedby", nullable = false)
    public PUseraccount getPUseraccountByModifiedby() {
        return this.PUseraccountByModifiedby;
    }

    public void setPUseraccountByModifiedby(PUseraccount PUseraccountByModifiedby) {
        this.PUseraccountByModifiedby = PUseraccountByModifiedby;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "createdby", nullable = false)
    public PUseraccount getPUseraccountByCreatedby() {
        return this.PUseraccountByCreatedby;
    }

    public void setPUseraccountByCreatedby(PUseraccount PUseraccountByCreatedby) {
        this.PUseraccountByCreatedby = PUseraccountByCreatedby;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="p_q_objekt_vorlage", nullable=false)
    public PQObjektVorlage getPQObjektVorlage() {
        return this.PQObjektVorlage;
    }

    public void setPQObjektVorlage(PQObjektVorlage PQObjektVorlage) {
        this.PQObjektVorlage = PQObjektVorlage;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "beschreibung")
    public String getBeschreibung() {
        return this.beschreibung;
    }

    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }

    @Column(name = "q_objekt_bewertung")
    public BigDecimal getQObjektBewertung() {
        return this.QObjektBewertung;
    }

    public void setQObjektBewertung(BigDecimal QObjektBewertung) {
        this.QObjektBewertung = QObjektBewertung;
    }

    @Column(name = "q_objekt_gewichtung")
    public BigDecimal getQObjektGewichtung() {
        return this.QObjektGewichtung;
    }

    public void setQObjektGewichtung(BigDecimal QObjektGewichtung) {
        this.QObjektGewichtung = QObjektGewichtung;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createdat", length = 19)
    public Date getCreatedat() {
        return this.createdat;
    }

    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "modifiedat", length = 19)
    public Date getModifiedat() {
        return this.modifiedat;
    }

    public void setModifiedat(Date modifiedat) {
        this.modifiedat = modifiedat;
    }

    @Column(name = "hinweis", length = 65535)
    public String getHinweis() {
        return this.hinweis;
    }

    public void setHinweis(String hinweis) {
        this.hinweis = hinweis;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "PQObjekt")
    public Set<PQKriterium> getPQKriterien() {
        return this.PQKriterien;
    }

    public void setPQKriterien(Set<PQKriterium> PQKriterien) {
        this.PQKriterien = PQKriterien;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "status", nullable = false)
    public PStatus getPStatus() {
        return PStatus;
    }

    public void setPStatus(PStatus PStatus) {
        this.PStatus = PStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "evaldat", length = 19)
    public Date getEvaldat() {
        return evaldat;
    }

    public void setEvaldat(Date evaldat) {
        this.evaldat = evaldat;
    }

    @Transient
    public List<PQKriterium> getKriteriumList() {
        List<PQKriterium> KriteriumList = new LinkedList<PQKriterium>();
        if (this.PQKriterien == null) {
            return KriteriumList;
        } else {
            for (PQKriterium o : this.PQKriterien) {
                KriteriumList.add(o);
            }
        }
        return KriteriumList;
    }

    public void setKriteriumList(List<PQKriterium> KriteriumList) {
        this.KriteriumList = KriteriumList;
    }

    @Override
    public boolean equals(Object object) {
        // Basic checks.
        if (object == this) {
            return true;
        }
        if (object == null || getClass() != object.getClass()) {
            return false;
        }

        // Property checks.
        PQObjekt other = (PQObjekt) object;
        if (hid == 0 ? other.hid != 0 : hid != other.hid) {
            return false;
        }


        // All passed.
        return true;
    }
}
