package de.affinis.pauline.hbm;
// Generated 04.07.2013 19:12:12 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Version generated by hbm2java
 */
@Entity
@Table(name="version"
    ,catalog="paulprod"
)
public class Version  implements java.io.Serializable {


     private int hid;
     private String versionsnr;

    public Version() {
    }

	
    public Version(int hid) {
        this.hid = hid;
    }
    public Version(int hid, String versionsnr) {
       this.hid = hid;
       this.versionsnr = versionsnr;
    }
   
     @Id 
    
    @Column(name="hid", unique=true, nullable=false)
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    
    @Column(name="versionsnr", length=10)
    public String getVersionsnr() {
        return this.versionsnr;
    }
    
    public void setVersionsnr(String versionsnr) {
        this.versionsnr = versionsnr;
    }




}


